### ISSUE TITLE
Exclude some instance from the Index

### ISSUE THREAD

**Issue by luxcem** [sabricot/django-elasticsearch-dsl#106]
Is it possible to exclude some instances (based on a attribute) from the index.

One example could be excluding unpublished articles from the index.

**Comment by sabricot** [comment]
Yes by overriding the `def get_queryset(self):` method in the Document. You filter in it.

**Comment by luxcem** [comment]
Ok thank you, it's not very clear in the readme maybe it is worth adding this information.

**Comment by dpinol** [comment]
The problem with get_queryset is that it's only applied when running the search_index command, but not for new django models.
Is there any way to perform this restriction for all models?

thanks

**Comment by dpinol** [comment]
for the record, this is how I did it. It works :-D
```
    @staticmethod
    def filter_thing(thing):
        if isinstance(thing, Message):
            return [thing] if should_index_msg(thing) else []
        elif isinstance(thing, List):
            return filter(should_index_msg, thing)
        elif isinstance(thing, QuerySet):
            return thing.filter(...)
        else:
            return thing

    def update(self, thing, refresh=None, action="index", **kwargs):
        return super().update(self.filter_thing(thing), refresh, action, **kwargs)
```
