### ISSUE TITLE
Support elasticsearch-dsl > 6.1.0

### ISSUE THREAD

**Issue by piedrahitapablo** [sabricot/django-elasticsearch-dsl#115]
I am not sure about this issue but `django-elasticsearch-dsl` does not work with `elasticsearch-dsl` versions higher than 6.1.0, it shows an import error for `DocType` and `DocTypeMeta`, apparently they were removed in newer versions of `elasticsearch-dsl`.

**Comment by sulami** [comment]
See https://github.com/elastic/elasticsearch-dsl-py/pull/930

**Comment by matali1** [comment]
[elastic/elasticsearch-dsl-py#930 ](elastic/elasticsearch-dsl-py#930 ) fixed problem with `DocType` but not `DocTypeMeta` so new version 6.2.1 still doesn't work

**Comment by safwanrahman** [comment]
This package was using an internal undocumented Metaclass of `elasticsearch-dsl`. I am working on a patch to not use the internal undocumented metaclass so its possible to use the latest version of `elasticsearch-dsl`

**Comment by lthibault** [comment]
@safwanrahman Any word on this?  Do you have an ETA?

**Comment by lthibault** [comment]
@safwanrahman No worries!  Happy to hear someone is taking care of it 😃 
Good luck with the major refactor -- we've all been there!
