### ISSUE TITLE
DocTypeMeta issue

### ISSUE THREAD

**Issue by tiagoarasilva** [sabricot/django-elasticsearch-dsl#116]
Hi, with the new version of elasticsearch >= 6.2 the DocTypeMeta was removed/renamed to `DocumentMeta`. I've tried to open a PR or even clone it but for some reason I couldn't.

Thanks,
Tiago

**Comment by domface** [comment]
+1

**Comment by jaddison** [comment]
Duplicate of #115.

**Comment by alaminopu** [comment]
@safwanrahman This issue has been discussed in #115 and resolved in #136. It should be closed in favor of #136

**Comment by tiagoarasilva** [comment]
If it was fixed, then the issue should be closed.
