### ISSUE TITLE
Indexing large amounts of data can cause memory leaks

### ISSUE THREAD

**Issue by cocoakekeyu** [sabricot/django-elasticsearch-dsl#118]
I plan to index 200,000 data(using search_index --rebuild), but by half of the data the memory is full.

![image](https://user-images.githubusercontent.com/4177398/42421118-046051fc-8303-11e8-9733-9035227caaa8.png)

**solution**:
Change [doc().update(qs)](https://github.com/sabricot/django-elasticsearch-dsl/blob/master/django_elasticsearch_dsl/management/commands/search_index.py#L92) to `doc().update(qs.iterator())`

**Comment by hrdymchl** [comment]
Yeah, we're facing something similar. Trying to index ~7MM documents and our machines exit with memory issues.

**Comment by sabricot** [comment]
Have you try to use the `pagination_queryset` attribute to split your queryset in chunks ?

```python
class MyDocument(DocType):
    class Meta:
        model = MyModel
        # The fields of the model you want to be indexed in Elasticsearch
        fields = [
            'name',
            ......
        ]
        queryset_pagination = 2000
```

**Comment by safwanrahman** [comment]
This has been fixed by https://github.com/sabricot/django-elasticsearch-dsl/pull/213
