### ISSUE TITLE
Multisearch rehydration

### ISSUE THREAD

**Issue by sulami** [sabricot/django-elasticsearch-dsl#120]
Hi,

I'm writing on behalf of @ostmodern, we're in the process of migrating from django-haystack to django-elasticsearch-dsl and would like to add object rehydration for multi-search. We're wondering if there have been any plans in this direction already, and if we would be to implement this in a fork whether we could get it merged back into mainline so we don't have to support our own version with updates? If you want to talk more about this in private, feel free to email me at robin.schroer@ostmodern.co.uk.

**Comment by safwanrahman** [comment]
Hi @sulami, Thanks a lot for the issue.
I think you can make changes and send a patch. I will be happy to review it.

**Comment by sulami** [comment]
Sorry for the late reply. We have gone a different route for now which doesn't require rehydration from multisearch, but thank you anyway.
