### ISSUE TITLE
Can't Understand how to use

### ISSUE THREAD

**Issue by may98ank** [sabricot/django-elasticsearch-dsl#127]
Hello I'm a student and new in Django and I am creating a project and want to use elasticsearch in it but I'm continuously getting new and different errors. I've read different articles and blogs, I've also seen some talks, but I couldn't get a clear idea how to use it for indexing and searching my database in Django.  Can you give me a example Project or any resource So, that I can clearly Understand what to do and how to do??
It would be very helpful, Thanks.

**Comment by robertpro** [comment]
Have you took the official [polls tutorial](https://docs.djangoproject.com/en/2.1/intro/tutorial01/) ?
