### ISSUE TITLE
How to set dynamic field mapping?

### ISSUE THREAD

**Issue by hrdymchl** [sabricot/django-elasticsearch-dsl#133]
Hi, thanks for the contribution! 

I'm wondering if there is a way to set `dynamic` parameter in this library? 

Elasticsearch by default [infers the datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html), which is causing mapping errors when ingesting data into a new index.

It would be great if we had the option to set it to `strict` or even `false`.

**Comment by safwanrahman** [comment]
Good point! I tink you can add `dynamic = MetaField('strict')` in the `Meta` class of the document and it should work.
Let me know if it does not work, and I will investigate it more!

**Comment by hrdymchl** [comment]
Hey @safwanrahman, thanks for the fast response! Awesome stuff :)

I just tested your suggestion, and, unfortunately, I'm getting `NameError: name 'MetaField' is not defined`

Here's a sample `Meta` class for one of our indexes. 

    class Meta:
        model = li_data_models.ESSpecificUseType
        dynamic = MetaField('strict')

**Comment by safwanrahman** [comment]
@hrdymchl You should import `MetaField` from `elasticsearch-dsl`
add `from elasticsearch_dsl import MetaField` and it should work!

**Comment by hrdymchl** [comment]
Ah, thanks - I was trying to import it from `django_elasticsearch_dsl`. 

I'm not sure that it is working. We have a field that is defined as `text`, but even after setting dynamic to `strict`, elasticsearch is still initially setting the data type as `date`.

I didn't see any new exceptions either.

What's really weird is that if we drop the index and then run `python manage.py search_index --rebuild`, then the field/schema is created correctly.

Why might this be the case? I would think that since this field is defined, it should always be defined as `text` by es.

**Comment by safwanrahman** [comment]
@hrdymchl Because you can not change the datatype without recreating the index in elasticsearch. so though you have changed in the elasticsearch-dsl end, it does not put the new mapping automatically. It only put the mapping when it creates the index.

so is it solve your issue?

**Comment by hrdymchl** [comment]
Right, I'm aware of that. I had tested this solution after dropping all existing indexes. It didn't prevent the field from mapping incorrectly nor did it throw an error. I'm just trying to understand why fields that are defined in our documents.py might map to a different datatype. That is exactly what we're trying to prevent, so if you have other suggestions, would be happy to give them a try.

**Comment by safwanrahman** [comment]
@hrdymchl can you share example of your document and any steps to reproduce?

**Comment by hrdymchl** [comment]
It might be kind of difficult.

```
@li_generic_document_type_idx.doc_type
class ESGenericDocumentTypeCompletion(ESTypeCompletionMixin, DocType):
    code = fields.KeywordField()
    title = fields.TextField()

    suggest = fields.CompletionField(analyzer=autocomplete_analyzer, search_analyzer=autocomplete_analyzer)

    class Meta:
        model = li_data_models.ESGenericDocumentType
        dynamic = MetaField('false')
```

**Comment by hrdymchl** [comment]
Sorry @safwanrahman, didn't mean to close it. Give me some time to get a reproduction ready for you. Our documents are kind of complex.

**Comment by hrdymchl** [comment]
@safwanrahman I'm closing this. `dynamic = MetaField('strict')` works as intended. It was my mistake.  Thanks for the help! :)

**Comment by dinesh1218** [comment]
@hrdymchl  @safwanrahman  I don't want to use `dynamic = 'strict'` since I don't want to throw any exception, instead I need to ignore the fields which are not in my mapping. As per this [document](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html) we can control it by adding `dynamic = 'false'`. But it's not working in my case, how to use `dynamic = false` . Below is my mapping

> {
>   "settings": {
>     "index": {
>       "number_of_shards": 3,
>       "number_of_replicas": 2
>     }
>   },
>   "mappings": {
>     "dynamic": false,
>     "properties": {
>       "id": {
>         "type": "keyword"
>       }
>     }
>   }
>   }

I'm using python package elasticsearch_dsl to update an document, I added the config like given below 

```
class Post(Document):
     title = Text()
 
     class Meta:
         all = MetaField(enabled=False)
         dynamic = MetaField('strict')

```

It worked for strict and not for false, how to add config for `dynamic = 'false'` ?
