### ISSUE TITLE
How do you search in multiple models with group by and pagination ?

### ISSUE THREAD

**Issue by kornikopic** [sabricot/django-elasticsearch-dsl#135]
Hello,

I am new to ElasticSearch and I'm struggling with the search feature. I have been able to search per document but not a group of documents. 

* How do you search into multi document at once? 
* And how do you group the result by type of document?

Please advise. Thank you.

**Comment by safwanrahman** [comment]
You should ask this question in elasticsearch support channel!

**Comment by johnyoonh** [comment]
@kornikopic this question is yet to be answered, but you could follow this issue https://github.com/sabricot/django-elasticsearch-dsl/issues/134
