### ISSUE TITLE
Index build memory and speed issue redux

### ISSUE THREAD

**Issue by mjl** [sabricot/django-elasticsearch-dsl#137]
I'm trying to trace down that slow indexing problem that is described in issues #118, #130 and #86.

As a first data point, I have an application that uses django-haystack that I'm trying to move over to DED. Indexing the same miniature data set takes about twice as long and consumes a load of memory.

Here is the indexing performance of haystack with a ~50k test data set:

    $ time python manage.py rebuild_index
    ...
    Indexing 48479 KIT+ plastic

    real	1m16.088s
    user	0m41.056s
    sys	0m1.186s

And here the absolute same for DED:

    $ time python manage.py search_index --rebuild
    ...
    Indexing 48479 'Plastic' objects

    real	1m57.927s
    user	1m8.748s
    sys	0m4.084s

Okay, about half as fast. Not ideal...

Now, on my integration machine, I tried to index a real world dataset of about 1.8M records. I aborted the index run after about 15mins, it used up **all memory** and swap, load was hovering at 18, the machine was totally unresponsive.

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    666 myself   20   0 3649612 3.330g     16 D   6.6 89.1   2:43.09 python

django-haystack takes about 18m for this same data set. Okay, we really have a problem.

I implemented the same queryset slicing I contributed to haystack (please refer to https://github.com/django-haystack/django-haystack/issues/1077#issuecomment-277677653 for details)
and added some more tweaks to disable Django's queryset caching mechanism.

Again, on the same integration machine as above, here are the results of
different improvements.

[1] Using PagingQuerySet:

This is a proxy queryset that uses iterator() which disables the Django
queryset cache (and uses a server side cursor for fetching data on postgres),
as well as slices the query into multiple parts to work around any caching
in the database driver (this happening is hinted to in the Django docs).

Load stays at around 1, memory usage was virtually constant at a reasonable 60M,
CPU usage is always around 75-80%.

    $ time python manage.py search_index --rebuild -f
    Deleting index 'cc.kitplus-20181116142151'
    Creating index 'cc.kitplus-20181116142151'
    Indexing 1784504 'Plastic' objects

    real	17m38.681s
    user	12m53.976s
    sys	0m14.652s

[2] Using parallel_bulk:

As nothing is actually using the return value from bulk(), I replaced it
with parallel_bulk and returned a dummy value. Errors will be raised as
exceptions anyway, so this does not make a difference.

This almost maxes out the CPU at 95-98%, ie. without parallelizing or optimizing
the prepare stage, this won't go any faster; it uses quite a bit more memory at 80M,
but still in a reasonable range.

    $ time python manage.py search_index --rebuild -f
    Deleting index 'cc.kitplus-20181116144037'
    Creating index 'cc.kitplus-20181116144037'
    Indexing 1784504 'Plastic' objects

    real	14m57.104s
    user	13m41.944s
    sys	0m27.508s

[3] Using precomputed prepare w/ bulk:

Instead of re-discovering the way to prepare each field while indexing,
compute that first and just re-use those preparation instructions.
The drawback is that you can no longer feed heterogenous data per model
to the index as they all need to have the same structure for the prepare step,
but as far as I can tell this can't happen anyway.

About the same performance improvement as using parallel_bulk, albeit with less
memory used. Exhibits the same memory and CPU behaviour as normal bulk index [1] above.

    $ time python manage.py search_index --rebuild -f
    Deleting index 'cc.kitplus-20181116145634'
    Creating index 'cc.kitplus-20181116145634'
    Indexing 1784504 'Plastic' objects

    real	14m41.170s
    user	9m59.996s
    sys	0m13.964s

[4] Using precomputed prepare w/ parallel_bulk:

Okay, all combined.

    $ time python manage.py search_index --rebuild -f
    Deleting index 'cc.kitplus-20181116151651'
    Creating index 'cc.kitplus-20181116151651'
    Indexing 1784504 'Plastic' objects

    real	12m1.882s
    user	10m48.872s
    sys	0m26.696s

So from totally impossible to index to 12m (django-haystack takes about 18m).

I'll clean up my experiments and make them available, please stay tuned.

**Comment by barseghyanartur** [comment]
@mjl:

Awesome! I'm looking forward to have it merged and released. Thank you!

**Comment by mjl** [comment]
Sorry for the wait, as usual, life interfered. Anyhow, I have cleaned my changes pertaining to indexing up and integrated them into the main tree, please have a look at

https://github.com/mjl/django-elasticsearch-dsl/tree/mjl-index-speedup

I invite anyone to check it out and see whether there are any bugs to shake out before requesting a merge. Feedback welcome.

Note that some tests are now failing with a strange connection error, this must come from the "parallel_bulk" change, but I have no idea what this means or why it is happening. Any hints are appreciated.

    ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x106185850>:        
    Failed to establish a new connection: [Errno 61] Connection refused) ...

**Comment by julzhk** [comment]
Sorry to report:
* my local tests appear to fail with a 'database table locked' error with your branch. (they pass again when I revert to release 0.5.1) 
* I'm using sqlite locally, with auto-sync=False.
* My tests are simple populate, by creating some test records and running search-index --rebuild... so nothing too unusual. 
Happy to provide more details if useful.

**Comment by mjl** [comment]
Cool, thanks for the feedback. As far as I can tell there is nothing 
specially anti-sqlite in my code... The "table locked" makes me think 
that it might be due to concurrency, though there is no writing to the 
database, ie. there should be no locks at all. Are you doing some 
writing or have transactions open while the index is running? Perhaps 
back out only the "parallel bulk" change, does that make it behave 
differently?

**Comment by julzhk** [comment]
Hi, 
Very keen to speed up indexing, so thanks for your contribution btw.

re: concurrency: yes that's entirely plausible but these tests aren't (explicitly) doing anything concurrent:
* the only writing to the database is:to set up the test state & elasticsearch. I'm not doing any database changes thereafter
* I'm guessing that it's the ingestion query - ie the 'get_queryset' query in the document definition, called in --rebuild maybe locking the table. 
* I'll look into it some more.

**Comment by mjl** [comment]
Is your test environment something that can easily be packed up? I don't 
really use sqlite so I don't have anything that could be used as a test 
bed readily available...

**Comment by mjl** [comment]
> * I'm guessing that it's the ingestion query - ie the 'get_queryset' 
> query in the document definition, called in --rebuild maybe locking 
> the table.

Can you try to set the queryset_pagination to some very high number, 
larger than the number of rows? That should effectively disable any 
parallelism but still disable django's queryset cache.

**Comment by mjl** [comment]
Perhaps also try to set the 'timeout' option to something ridicuously large, like 30 seconds or so, as hinted at by https://docs.djangoproject.com/en/2.1/ref/databases/#database-is-locked-errors

**Comment by mjl** [comment]
Ok, I just made the usage of parallel_bulk configurable via the parallel_indexing Meta option, so if you update the branch it should now not use anything concurrent by default. You have to explicitely opt in by setting parallel_indexing=True.

**Comment by mjl** [comment]
Note that this also fixes the test failures I mentioned above, so I guess the tests also are not ready for parallelism.

**Comment by fkoksal** [comment]
Using @mjl 's branch I was able to index 1M user objects in 18mins.
But it exited with 'Killed' message for 3M products.

Any idea how to debug the process?

**Comment by mjl** [comment]
This sounds as if you are running into some kind of resource limitation, perhaps open files or stack size or whatever. Perhaps the system's log file have more details? Also look at ulimit, perhaps something is set rather tight and could be bumped up?

Though I have no idea what the difference between indexing 1M and 3M should be, resourcewise. It could be that ES is using more memory so there is less left over for your indexing process, are you running both ES and the indexing on the same machine?

**Comment by fkoksal** [comment]
I have set 'queryset_pagination = 20000' and I don't get the error anymore. I guess it was the app server trying to get more products from the db than he can fit in his memory.

Currently, with the queryset_pagination set to 20K, it takes 15hours to index 3M products.

What I can see from the ES is, every 7 seconds 500 products are bulk indexed. So, there should be a hard coded '500' somewhere (independent from the queryset_pagination setting).

I am going to play with those numbers to see how they effect the indexing speed.

**Comment by mjl** [comment]
Glad you sorted it out. I have not seen any substantial gains from batch sizes larger than 10k, so if you are on a memory starved machine, you can probably reduce your 20k without much impact.

You can also try to turn on parallel indexing, that may increase indexing throughput, but will increase memory consumption a bit.

**Comment by fkoksal** [comment]
Back to the basics: I am now using a simple python script, which;
- takes the input directly from postgresql
- adds index lines required by elasticsearch bulk request
- sends the file to elasticsearch bulk request API.

For 3M records, it reduced the indexing time from 15 hours to 6 mins.

Seems that processing files is way faster than serializing objects.

**Comment by mjl** [comment]
Interesting. In my tests, serialization has a measurable impact, about 30% -- and that's the reason for pre-computing the field serializing functions -- but those timings are ridiculous. You are sure you aren't doing things like following foreign keys in your serializers by accident? You absolutely need a select_related in your queryset definition or else things go pear shaped very quickly.

I ran an import on my production machine today and it imported short of 2M records in 9 minutes. The serializers are not very complicated, string concats and stuff, but I can't imagine anything that would increase that by several orders or magnitude.

**Comment by fkoksal** [comment]
@barseghyanartur Sure. Let me first refactor it, so that it's a little bit configurable.

@mjl I haven't wrote the DocTypes and serializers, but, they seem to be OK. I will check them in more detail after we are done with the migration. Will let you know.

**Comment by abdelwahebmoalla** [comment]
@fkoksal any updates?

**Comment by barseghyanartur** [comment]
@mjl:

With no changes to the code, pagination size or something (but with parallel indexing), I get a speed boost of 2/3 of the original (12 minutes against 32 minutes) for 1.6 million records. Thank you!

**Comment by abdelwahebmoalla** [comment]
@mjl is your version safe for prod mode ?

**Comment by mjl** [comment]
> @mjl is your version safe for prod mode ?

   It works for me without any problems so far, but of course it has not 
gotten a lot of exposure to other environments, so you might very well 
run into a problem that doesn't occur with my use case. But I think the 
code is rather solid.

**Comment by abdelwahebmoalla** [comment]
@mjl sorry for bothering you but I am unable to download your version

**Comment by barseghyanartur** [comment]
@abdelwahebmoalla:

Does `pip install https://github.com/mjl/django-elasticsearch-dsl/archive/mjl-index-speedup.zip` not work for you?

**Comment by barseghyanartur** [comment]
FYI. I've been running this in production for a couple of months already.

**Comment by safwanrahman** [comment]
It has been fixed by https://github.com/sabricot/django-elasticsearch-dsl/pull/213

**Comment by mathijsfr** [comment]
I need to index 80 million documents and my system can't handle it. It crashes at 100% ram usage. (About 12gb of ram).
