### ISSUE TITLE
Querying documents from ES and populating django model to use in REST endpoints

### ISSUE THREAD

**Issue by philippbussche** [sabricot/django-elasticsearch-dsl#14]
Hi there, I have a django rest application and need to query documents from ElasticSearch so that I can expose them. I was looking at this project to help me achieving what I am after, however besides just querying the data through my documents module I would have to deserialize the documents into my model and that hook that up to my rest views. Would you know how I could achieve this ?
Thanks.

**Comment by sabricot** [comment]
Hello,
Unfortunately, there is no way in this package to generate a django Model instance from an ElasticSearch result.
I think it's a nice feature to add, but i don't know how hard it would be to implement, especially for manage relations and custom attributes.

If your model is really simple you can just do something like this:

```python
[MyModel(**hit.to_dict()) for hit in MyDocument.search().query()]
```
But this will not work for relations and custom attributes added to the Document

If you use django rest framework for your rest views you can use a custom serializer. I have an example if you want ?

**Comment by philippbussche** [comment]
Hi there, thank you for your answer. I went with the custom serializer since I am doing Django REST. Thanks again !
