### ISSUE TITLE
TypeError: Object of type 'InnerDoc' is not JSON serializable

### ISSUE THREAD

**Issue by dco5** [sabricot/django-elasticsearch-dsl#140]
Hello I am getting the error TypeError: Object of type 'InnerDoc' is not JSON serializable when trying to return the results in a Response() using DRF for a NestedField().

Document:
_class PeopleDocument(DocType):
    ...
    connections = fields.NestedField(properties={
        'id': fields.IntegerField(),
        'status': fields.TextField(analyzer='keyword'),
        'profile_from': fields.IntegerField(attr='profile_from_id'),
        'profile_to': fields.IntegerField(attr='profile_to_id'),
        'sender': fields.BooleanField(),
        'created': fields.DateField()
    }, attr='get_connections')
    ..._
Not really sure what is going on, I followed the example app in the repo and it does something similar with Ad and Categories.

Thanks!

**Comment by appli-intramuros** [comment]
How did you resolve this issue ?

**Comment by dco5** [comment]
Hello @appli-intramuros 

I am using DRF to return the search results so I created 

class JSONSearchEncoder(JSONEncoder):
    def default(self, obj):
        from elasticsearch_dsl import InnerDoc
        if isinstance(obj, InnerDoc):
            return obj.to_dict()
        return super().default(obj)


class JSONSearchRenderer(JSONRenderer):
    encoder_class = JSONSearchEncoder

class GeneralSearchAPIView(APIView):
    renderer_classes = (JSONSearchRenderer,)
