### ISSUE TITLE
document field like haystack

### ISSUE THREAD

**Issue by DannyAziz** [sabricot/django-elasticsearch-dsl#150]
Hi, I'm trying to move my project over from haystack, I was wondering if it was possible to have a field like haystacks "document" field that follows a template?

To provide more context I want my users to be able to search multiple fields in one search bar, so, for example, they could search "Blue Bag" and it would search on both the `color` and `category` fields.

Thanks

**Comment by barseghyanartur** [comment]
@DannyAziz:

To move away from haystack you should first stop thinking in "haystack".

TL;DR: You can search on multiple fields in your code. The subject is too broad for the ticket. My advice - gain some Elasticsearch knowledge. You can start with [elasticsearch-dsl](https://elasticsearch-dsl.readthedocs.io/en/latest/).

**Comment by DannyAziz** [comment]
@barseghyanartur That's exactly what I ended up doing! Thanks!
