### ISSUE TITLE
User as SimpleLazyObject not possible to index

### ISSUE THREAD

**Issue by ruddy2442** [sabricot/django-elasticsearch-dsl#155]
Hi, I am having troubles indexing the User when user object has been got from request (and authenticated over default modelbackend auth). Django uses its SimpleLazyObject and django dsl crashes somewhere in  django_elasticsearch_dsl/fields.py:get_value_from_instance() on line 127 with error {TypeError} 'User' object is not iterable. When user is passed to indexer as User from DB, indexing works, when its passed from request.user, it does not work (thats the case, when we are creating object with relation to user and user is passed to create method as request.user - SimpleLazyObject). Than the signal is called on instance to index, but objects is still the SimpleLazyObject, instead of user.

**Comment by abdelhalimresu** [comment]
@ruddy2442, I believe it's the same issue I was facing.
I resolved it by using the `request.user.id` instead of `request.user` when creating an object which depends on the user object like this:
```python
object = YourModel(**kwargs, user_id=request.user.id)
object.save()
```
instead of
```python
object = YourModel(**kwargs, user=request.user)
object.save()
```

**Comment by manishkumr** [comment]
I am exactly having the same issue while trying to save a model which has User model as a foreign key.  I have got this working as suggested by @ruddy2442 , will there be any fix available for this?

**Comment by mboudet** [comment]
Same issue here. In one of my model, I manually set the created_by field to the user making the request. The field is populated with request.user in form_valid.

Indexing an existing entity works fine, but creating a new one crashes with "'User' object is not iterable"

A workaround was to use get_user(request) to get the 'real' user and not the lazy object.

While it isn't much trouble, the error thrown by django-elasticsearch-dsl is not very clear. it might be good to add to the documentation that 'request.user' cannot be used by itself at entity creation?
(And all SimpleLazyObjects)

**Comment by hemache** [comment]
A quick workaround would be to fix `ObjectField` by handling `SimpleLazyObject`s gracefully 

```
from django.utils.functional import SimpleLazyObject
from django_elasticsearch_dsl import fields

class MyObjectField(fields.ObjectField):
    def get_value_from_instance(self, instance, field_value_to_ignore=None):
        objs = fields.DEDField.get_value_from_instance(self, instance, field_value_to_ignore)

        if objs is None:
            return {}
        if not isinstance(objs, SimpleLazyObject) and isinstance(objs, collections.Iterable):
            return [
                self._get_inner_field_data(obj, field_value_to_ignore) for obj in objs if obj != field_value_to_ignore
            ]

        return self._get_inner_field_data(objs, field_value_to_ignore)

class MyDocument(...):
    my_user_field = MyObjectField(...)
```
