### ISSUE TITLE
Create index in different files which contain different models

### ISSUE THREAD

**Issue by gargayush341** [sabricot/django-elasticsearch-dsl#162]
How can I create indexing of different models which are in different python files, basically how to pass the file name as a parameter when running the command **search_index --rebuild**

**Comment by barseghyanartur** [comment]
Use `--models` directive. [The code](https://github.com/sabricot/django-elasticsearch-dsl/blob/master/django_elasticsearch_dsl/management/commands/search_index.py#L11).

**Comment by gargayush341** [comment]
Thankyou soo much
