### ISSUE TITLE
Changing the _id meta field

### ISSUE THREAD

**Issue by felubra** [sabricot/django-elasticsearch-dsl#171]
Using `DocType`, is there a way to define which field in the model is used as the source for the `_id` metafield in the ES index? 
I am in a situation where I cannot change the model PK field and nevertheless want to prevent the harvesting of the data by successive gets into successive id numbers: /_doc/1, /_doc/2 etc.

**Comment by PAStheLoD** [comment]
You might be able to hack around this by defining your own _prepare_action on your class, forwarding to the super class' method, and removing the _id before returning, that way ES will autogenerate the id.

**Comment by felubra** [comment]
@PAStheLoD thank you! I'll try that out.

**Comment by safwanrahman** [comment]
@felubra You can define your own `_prepare_action` method in document class and set the `_id` as per your logic. Do not keep the `_id` blank, otherwise the data will be append always, never get updated

**Comment by quiin** [comment]
Note that specifying a different id **may** break the `to_queryset()` function since objects are retrieved using the `_id` meta field
```python
def to_queryset(self, keep_order=True):
        ...
        pks = [result.meta.id for result in self]
        qs = self._model.objects.filter(pk__in=pks)
        ...
```

**Comment by Sachin-Kahandal** [comment]
Somethings up with id, though I havent made any chaanges in to_queryset function

s = MyntraClothesDocument.search(index="myntra_clothes").query(MultiMatch(query=text, fields=['Title', 'Description'], operator="AND", fuzziness='AUTO'))
qs = s.to_queryset()

ValueError: Field 'id' expected a number but got '41jl7ngByXlYCcE8rXBp'.
