### ISSUE TITLE
Transport Error - Result window is too large

### ISSUE THREAD

**Issue by hitz02** [sabricot/django-elasticsearch-dsl#173]
I am unable to execute a search for around 35000 records. I am getting the following error -

TransportError(500, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [35846]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')

Can someone please guide me where should I change the max_result_window settings or how to use scroll API with Django models?

Below is the code that I am working on - 
candidatesDoc = CandidateDocument.search().query("match", Resume_text=JD_nouns)
candidates = candidatesDoc[0:CandidateDocument.search().count()].execute()

Note - the count here is ~35k

Below is my documents.py -

# Name of the Elasticsearch index
candid = Index('candidates')
# See Elasticsearch Indices API reference for available settings
candid.settings(
    number_of_shards=2,
    number_of_replicas=0,
    max_result_window = 50000 #thought of adding here but it doesnt work
)

@candid.doc_type
class CandidateDocument(DocType):
    class Meta:
        model = Candidates # The model associated with this DocType

        # The fields of the model you want to be indexed in Elasticsearch
        fields = [
            'id',
            'Name',
            'Company_Name',
            'Designation',
            'College_Name',
            'Degree',
            'Skills',
            'Resume_text'
        ]

This is urgent. Let me know if any other detail is required.
Any help will be appreciated.

Thanks

**Comment by safwanrahman** [comment]
you should use pagination lower tha 500 I think

**Comment by hitz02** [comment]
Yeah, how do we mention that in the code?
