### ISSUE TITLE
Can we get a Pypi release for the new version?

### ISSUE THREAD

**Issue by josh-stableprice** [sabricot/django-elasticsearch-dsl#177]

**Comment by safwanrahman** [comment]
It depends on the main author @sabricot. He has the access to Pypi for the package `django-elasticsearch-dsl`.

@sabricot can you publish the latest release to Pypi?

**Comment by Acetonen** [comment]
@safwanrahman is Sabricot alive?

**Comment by safwanrahman** [comment]
@Acetonen I hope nothing is wrong with him, maybe he is just busy with his life.
I have emailed him, but no response from him yet!

**Comment by josh-stableprice** [comment]
@safwanrahman it may be worth setting up a pypi fork as you have the most access of anyone else here.

**Comment by matthiaskoenig** [comment]
+1

**Comment by safwanrahman** [comment]
I have got "Maintainer" access in Pypi for django-elasticsearch-dsl. Thanks a lot @sabricot 
I will release it to pypi soon.

**Comment by safwanrahman** [comment]
I have released version `6.4.1` in Pypi. Thanks a lot everyone including @sabricot for giving me the access in Pypi.
https://pypi.org/project/django-elasticsearch-dsl/6.4.1/
