### ISSUE TITLE
cannot import name 'Document'

### ISSUE THREAD

**Issue by ochui** [sabricot/django-elasticsearch-dsl#180]
**Development Environment**
Python3 (3.5.3).
Django 2.2.1.
django_elasticsearch_dsl 0.5.1

```
from django_elasticsearch_dsl import Document
from django_elasticsearch_dsl.registries import registry


@registry.register_document
class CarDocument(Document):
    class Index:
        # Name of the Elasticsearch index
        name = 'cars'
        # See Elasticsearch Indices API reference for available settings
        settings = {'number_of_shards': 1,
                    'number_of_replicas': 0}

    class Django:
        model = Car # The model associated with this Document

        # The fields of the model you want to be indexed in Elasticsearch
        fields = [
            'name',
            'color',
            'description',
            'type',
        ]

```

looking into the file _django_elasticsearch_dsl.documents_ the Documents class is'nt define, it looks like someone updated the doc too early.

**Comment by safwanrahman** [comment]
@ochui You should install the `django-elasticsearch-dsl` as per mentioned in the docs. not from pypi

**Comment by muneebshahid** [comment]
I am installing using `pip install https://github.com/sabricot/django-elasticsearch-dsl/archive/6.4.0.tar.gz` The issue still remains, upon opening the code tagged 6.4.0 one can see class "Document" is not presetn in "django_elasticsearch_dsl.documents"

**Comment by ochui** [comment]
@safwanrahman You should try it out your self. I have followed the instructions on the docs.

**Comment by safwanrahman** [comment]
There is a mistake in the code, we need to have a alias of `Documen` in `DocType`. As a workaround, you can use `DocType` untill I push a release!
