### ISSUE TITLE
6.4.0 issues -  cannot import name 'Document'

### ISSUE THREAD

**Issue by ghferrari** [sabricot/django-elasticsearch-dsl#182]
There seem to be several issues with the 6.4.0 release.
1.  README.rst suggests one should have the following in documents.py:

```
# documents.py
from django_elasticsearch_dsl import Document
from django_elasticsearch_dsl.registries import registry
```

However, this gives the error:

`ImportError: cannot import name 'Document' from 'django_elasticsearch_dsl`

2. Although README.rst and requirements.txt seem to require e.g. elasticsearch-dsl>=6.4.0,<7.0.0 , running the suggested command `pip install https://github.com/sabricot/django-elasticsearch-dsl/archive/6.4.0.tar.gz` results in the installation of elasticsearch-7.0.2.

3) Can someone please clarify: is this release intended for use with ES7 or not?

Thanks for your help,

Geoff

**Comment by safwanrahman** [comment]
Sorry, I have fixed it with latest version!

**Comment by budescode** [comment]
> Sorry, I have fixed it with latest version!

what verson are you using?

**Comment by mbrsagor** [comment]
> > Sorry, I have fixed it with latest version!
> 
> what verson are you using?

from django_elasticsearch_dsl.documents import Document
