### ISSUE TITLE
How to setup a parent-child relationship?

### ISSUE THREAD

**Issue by dojutsu-user** [sabricot/django-elasticsearch-dsl#186]
I want to setup a parent child relationship just like -- https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/parent_child.py
Is there a way to do it?

**Comment by zaqk** [comment]
Bump. Could really use an answer on this question.

**Comment by safwanrahman** [comment]
This is more likely a question for `elasticsearch-dsl` than `django-elasticsearch-dsl`. I have no idea about implementation of this in `elasticsearch-dsl`

**Comment by safwanrahman** [comment]
I think it can be implemented like the one provided in `elasticsearch-dsl`. There are very few thing that we can do from this package end.
