### ISSUE TITLE
How to specify a field indexed = false and store = true

### ISSUE THREAD

**Issue by pavan538** [sabricot/django-elasticsearch-dsl#188]
Hi,

I have a django haystack  Field as follows 

`corousal_image_1 = indexes.CharField(model_attr='corousal_image_1', indexed=False, stored=True)`

now i need to convert the following field in to django elasticsearch dsl field
How can i specify that the field is not indexed and it is stored.

**Comment by safwanrahman** [comment]
I think, for this purpose you should see the documentation of [`elasticsearch-dsl`](https://elasticsearch-dsl.readthedocs.io/en/latest/api.html)

I think the same will work for `elastisearch-dsl` as well.
