### ISSUE TITLE
Prevent auto index on save

### ISSUE THREAD

**Issue by MiltosD** [sabricot/django-elasticsearch-dsl#189]
Ok, this is maybe more a question, than an issue. 
I have a model `X` for which I have created a respective `DocType`. This model has a field `status`. The` get_queryset()` method of the `DocType` is overridden so that only `X` instances with status `"public"` should be indexed. When an `X` instance is created the status field gets the value `"private"`. However, the instance is automatically indexed. 

So, how can I prevent auto indexing upon creation, or even better, indexing upon a condition?

Thank you

**Comment by safwanrahman** [comment]
This is a good feature that need to be implemented. We have done similar kind of things in Read The Docs.

**Comment by SanderTuit** [comment]
I think this is a duplicate for https://github.com/sabricot/django-elasticsearch-dsl/issues/111.

**Comment by safwanrahman** [comment]
Yeah. Seems like I opened #111 
closing in favor of #111
