### ISSUE TITLE
HISTORY.rst is out of date

### ISSUE THREAD

**Issue by SimKennedy** [sabricot/django-elasticsearch-dsl#192]
Hi, 
Thank you for the work on this package. 
I just wanted to remind you to update the change history..
I've just had to hunt around for a while to fix issues with dependencies which would have been a lot easier with an up to date HISTORY and list of breaking changes.
Thanks
Sim

**Comment by sciyoshi** [comment]
@SimKennedy I'm going through a similar process right now. From what I can tell, there's two major breaking changes:

* the `DocType` import has changed to `Document`
* `class Meta` has changed to `class Django`

@safwanrahman it would be great to know if anything else was a breaking change in the v6 update.

**Comment by safwanrahman** [comment]
Sorry I could not manage time to update `HISTORY.rst`.
@sciyoshi I think you need to use the `register_document` decorator to registar a document is missed. other than that, I think its ok!
Can you add them in history and make a PR?
