### ISSUE TITLE
Sprint at pyconfr 2019 ?

### ISSUE THREAD

**Issue by alexgarel** [sabricot/django-elasticsearch-dsl#199]
*Sorry I make an issue for this but I did'nt see any mailing list*

I will attend [pyconfr](https://www.pycon.fr/2019/) in Bordeaux from 31 oct to 3 nov 2019.

My company is using django-elasticsearch-dsl and I would like to propose sprinting to help the project. Sprints happens on thur 31 oct and fri 1 nov, but I will be there only on friday.

Some goals could be : 

- making a buildable documentation with sphinx to be hosted on readthedocs
- fixing some simple issues (or complex one, if we are confident)
- reviewing some PR

I also proposed a conference on using ElasticSearch with python in general where I will briefly talk about django-elasticsearch-dsl.

@sabricot and @safwanrahman, or others:

- if you are aware of people that may be interested in taking part, please let me know
- if there are important and/or easy issues you want to point me at
- if someone want to participate remotely, be it for just a moment, welcome.
- is there some mailing list and/or chat, that I'm not aware of ?

**Comment by safwanrahman** [comment]
Hi @alexgarel thanks for taking the effort. It is really helpful for this package as well as whole community. The goals are really impressive and I would love to help on this. I have claimed `django-elasticsearch-dsl` in `readthedocs`, so I can setup a basic doc setup in there.

> - if you are aware of people that may be interested in taking part, please let me know

I would love to join but can not join there as it will be costly for me to join there and the time for applying financial support is over. Maybe @sabricot or any other contributor can join

> - if there are important and/or easy issues you want to point me at
I will try to find some easy issue and let you know if I can find any

> - if someone want to participate remotely, be it for just a moment, welcome.

If remote is ok, I can try to participate at that time. Let me know the date and the time with timzone.

> - is there some mailing list and/or chat, that I'm not aware of ?

There is no mailing list or chat unfortunately. But if you need synchronous communication with me, I am available at telegram [@safwan](https://telegram.me/safwan)

**Comment by safwanrahman** [comment]
@alexgarel Do you have anything to know more? I am going to close the issue then!

**Comment by alexgarel** [comment]
No it's ok to close the issue :-) Thanks and hope to reach you with work done, and that I won't be alone that day in the sprint !
