### ISSUE TITLE
Elasticsearch Aggregation Composite

### ISSUE THREAD

**Issue by ozanteoman** [sabricot/django-elasticsearch-dsl#200]
Hello , i am using aggregations and aggregation bucket accept one key value as default then i research and find it

```{
    "aggs" : {
        "my_buckets": {
            "composite" : {
                "sources" : [
                    { "category_pk": { "terms": { "field": "category.pk"} } },
                    { "category_name": { "terms": {"field": "category.name" } } }
                ]
            }
        }
    }
}
```
Above code result two keys , and _doc_count but i can't apply for elasticsearch-dsl
Someone help me
- `Thanks`

**Comment by safwanrahman** [comment]
@ozanteoman Thanks for the issue. I think this kind of issue is good place for stackoverflow not issue tracker.

**Comment by ozanteoman** [comment]
@safwanrahman Thanks
