### ISSUE TITLE
Remove old elasticsearch versions compatibility

### ISSUE THREAD

**Issue by alexgmin** [sabricot/django-elasticsearch-dsl#201]
Is there a reason for this type of compatibility code? If every version only supports the corresponding major one I don't see a reason not to remove it, specially the ES2 one.
https://github.com/sabricot/django-elasticsearch-dsl/blob/addce06166dd31a052316e07b44736b451779f75/django_elasticsearch_dsl/fields.py#L213-L252

I'll be happy to make a pull request to at least remove it from 7.x branch

**Comment by safwanrahman** [comment]
Would be awesome you submit a PR.
