### ISSUE TITLE
postgis and geodjango support ?

### ISSUE THREAD

**Issue by psworld** [sabricot/django-elasticsearch-dsl#204]
How to get search results by ordering from nearest to farthest. How to use `dwithin()`. How to index with location.

```python
from django.db import models
from django.contrib.gis.db.models.fields import PointField

class Product(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=255)
    location = PointField(srid=4326, geography=True)
```

**Comment by alexgarel** [comment]
Hi @psworld, the bug tracker is for tracking bugs only.

If you need help you should try using Stackoverflow [using tags django and elasticsearch-dsl](https://stackoverflow.com/questions/tagged/django+elasticsearch-dsl)

If you'are ok with that, close the ticket eventually giving the link to your post on such forum.

**Comment by psworld** [comment]
hey @alexgarel thanks for looking into it.
[Here is the link](https://stackoverflow.com/questions/57883238/how-to-index-search-results-on-location-bases-not-the-whole-model-django)
