### ISSUE TITLE
Root mapping definition has unsupported parameters.

### ISSUE THREAD

**Issue by christianmtr** [sabricot/django-elasticsearch-dsl#207]
I have an `User(AbstractUser)` model and this document:
```
# documents.py

from django_elasticsearch_dsl import Document
from django_elasticsearch_dsl.registries import registry
from ... import User

@registry.register_document
class UserDocument(Document):
    class Index:
        name = 'users'
        settings = {'number_of_shards': 1,
                    'number_of_replicas': 0}

    class Django:
        model = User
        fields = ['first_name', 'last_name']
```

When I ran `search-index --rebuild` I'm getting this error:
```
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [last_name : {type=text}] [first_name : {type=text}]')
```

I thought `documents.py` is correct, based on `README.md` example.
Is there anything wrong?

**Comment by safwanrahman** [comment]
Which elasticsearch version you are currently using?

**Comment by christianmtr** [comment]
I'm using docker-compose service with:
`docker.elastic.co/elasticsearch/elasticsearch:6.4.3`

pip installs:
```
elasticsearch==7.0.4
elasticsearch-dsl==7.0.0
django-elasticsearch-dsl==7.0.0
```

Well I think that's the problem, right?? My partner setted up the service and I didn't review it.

**Comment by safwanrahman** [comment]
You are using elasticsearch 6.x with elasticsearch 7.x client library. Thats not ideal
