### ISSUE TITLE
Duplicate entries when insert to a model fails

### ISSUE THREAD

**Issue by samiullah452** [sabricot/django-elasticsearch-dsl#209]
I have a model in which a field is suppose to be unique. I sometimes get entries which have duplicate values for the field. I have a unique constraint on my database(besides elasticsearch), due to the unique constraint, the entry is not saved in the database but it gets saved in elasticsearch. Is there a way to enforce uniqueness or to ensure whether insert is done correctly or not in the database only then make insert in elasticsearch

**Comment by safwanrahman** [comment]
If the entry is not saved in database, it would not enter into elasticsearch if you are using `django-elasticsearch-dsl` auto indexing. As far as I know, there are no unique datatype in Elasticsearch rathar than ID.
