### ISSUE TITLE
How to automatically check if the index is present or not

### ISSUE THREAD

**Issue by venomone** [sabricot/django-elasticsearch-dsl#210]
Hello,

I want to automatically check and create (if not existing) the elasticsearch index of my app on startup, this is my current situation which is not working:

```
echo "Checking if Elasticsearch index is setup"
{
cat <<EOF | python /manage.py shell
from elasticsearch import Elasticsearch
HOST_URLS = ["elasticsearch:9200"]
es_conn = Elasticsearch(HOST_URLS)
INDEX_NAME = "posts"
res = es_conn.indices.exists(index=INDEX_NAME)

if res == True:
  print("Elasicsearch index seems already setup, skipping")
else:
  print("Elasicsearch index not setup yet, creating ...")
  import subprocess
  subprocess.Popen("y | python manage.py search_index --rebuild", shell=True, stdout=subprocess.PIPE).communicate()[
                0].decode('utf-8').strip()
EOF
}>/dev/null
```
which again results in:

"the '{}' indexes? [n/Y]: ".format(", ".join(index_names)))
| EOFError: EOF when reading a line

Does smb. maybe has a good snipped to solve this issue?

**Comment by alexgarel** [comment]
try to add `--noinput` to the rebuild command.

Also instead of using Popen, you can use https://docs.djangoproject.com/en/2.2/ref/django-admin/#running-management-commands-from-your-code
