### ISSUE TITLE
Custom analyzer not work with the latest version of elastic search

### ISSUE THREAD

**Issue by raisulkutumbita** [sabricot/django-elasticsearch-dsl#214]
For fully test with elastic search 6.x, django-elastic-search-dsl 6.x custom analyzer works fine. But when I upgrade to 7.x for those its not work. Its Raise BulkIndexError.

**Comment by alexgarel** [comment]
Hello @raisulkutumbita, are you sure the problem is on the library side ? 

Did you check the filters and tokenizers you use in your analyzers are still available in elastic 7 ?

If you still have the problem, you'll have to be more precise: please give us, useful excerpts of the code you run, the complete stack-trace and eventual logs from ES.

**Comment by raisulkutumbita** [comment]
Hi @alexgarel thanks for response. Mainly I follow the documentation of elastic-search-dsl, Django-elastic-search-dsl and django-elastic-search-dsl-drf. I just wrote my code by following the documentation and use this analyzer.... 

```
html_strip = analyzer(
        'html_strip',
        tokenizer="standard",
        filter=["standard", "lowercase", "stop", "snowball"],
        char_filter=["html_strip"]
)
```

```
@registry.register_document
class WorkerDocument(Document):
    id = fields.IntegerField()
    uuid = fields.KeywordField()
    name = fields.StringField(
        analyzer=html_strip,
        fields={
            'raw': fields.StringField(analyzer='keyword'),
        }
    )
```

And I just testing it by upgrading and downgrading version of all library by maintaining the compatibility. From this testing I am reach this decision. The problem is arising when I try to run the `re-index` command.

**Comment by safwanrahman** [comment]
@raisulkutumbita Can you please provide what kind of error you get? I do not know about django-elasticsearch-dsl-drf package, so can not comment for this. Without error trace, its not possible to debug any issue

**Comment by safwanrahman** [comment]
Ok. So from your mapping it seems like you are using `standard` token filter. [It has been removed in Elasticsearch 7.x.](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenfilter.html) Removing the `standard` filter fix your issue.

**Comment by raisulkutumbita** [comment]
@safwanrahman thank you very much. Its fixed.
