### ISSUE TITLE
management command default prompt

### ISSUE THREAD

**Issue by ArtyomSliusar** [sabricot/django-elasticsearch-dsl#215]
Hi,

Noticed a small issue when running the command:  
`./manage.py search_index --rebuild`

It returns:

> Are you sure you want to delete the '<elasticsearch_dsl.index.Index object at 0x7fdb578f02b0>' indexes? [n/Y]:

and if I hit enter without any input, it aborts further processing as if I used `n`, but default is `Y` according to the question.

I guess the command should be fixed to match the question's default prompt.

**Comment by safwanrahman** [comment]
How you are assuming that the default is `Y`?

**Comment by safwanrahman** [comment]
@ArtyomSliusar It would be nice if you get any kind of specification for this! 😉
