### ISSUE TITLE
Problem of to_queryset()

### ISSUE THREAD

**Issue by playma** [sabricot/django-elasticsearch-dsl#223]
The count of data is not consistent after `to_queryset()`
```
        print(restaurant_document.count())  # 8351
        queryset = restaurant_document.to_queryset()
        print(queryset.count())  # 10
```

**Comment by alexgarel** [comment]
Hi @playma, `to_queryset` is a limited feature. It just takes ids from your ES request and use them to make a request on the model. 

As you did not specify a slice on ` restaurant_document`, ES limits results to 10 items, hence the `count` of `queryset`.

If you want the `count` use the ES query, not `queryset`. 

`to_queryset` is really just an helper to retrieve objects corresponding to your research in the database.

You may propose an update to documentation if you feel it can help others.

**Comment by playma** [comment]
@alexgarel Thank you for your replay.
Actually, I want to get all the document data, and convert it to quueryset, then I can use the queryset to do filter or anything, is it possible? Maybe there is a better method to do this?

**Comment by alexgarel** [comment]
@playma this is not a good thing to do.

If I had to do this, I would rely on the database indice, use `scan` to be efficient. 

Maybe you can go something like this:

```python
from itertools import islice

def iter_queryset(es_query, batch_size=200):
    es_result =  es_query..source(excludes=['*']).scan()
    while True:
        pks = [r.meta.id for r in islice(es_result, 0, batch_size)]
        if not pks:
            break  # end of the search
        yield es_query._model.objects.filter(pk__in=pks)
        record.meta.id
 ```

This will give you an iterator, returning querysets by batch. If you directly want the objects, you may use a `yield from` instead of `yield`

You could also pass a base_queryset, instead of using `es_query._model.objects.` if you wan't to do more specific stuff.

Also note that here, I am using `scan` which is more efficient but does not support sorting.

**Comment by playma** [comment]
@alexgarel, thx
I rely on elasticsearch to search the huge data, and wants to do something after that.
If I relay on database, it will be very slow...

And there is no way to convert the data from document to queryset.

I have about 180k restaurant data, and I want to search by location, name filter by type, and other field. 
Do you have any idea?

Thanks again.

**Comment by alexgarel** [comment]
@playma Why don't you store the data you need in elasticsearch and then use the information directly ?
If you need aggregations, elasticsearch is very capable, see [ElasticSearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html) and [How to use it with elasticsearch-dsl](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#aggregations)

**Comment by playma** [comment]
@alexgarel Thank you for your help, I will try it.

**Comment by playma** [comment]
@alexgarel I have two more questions.
1. Can I get the query(request) of the elasticsearch dsl for debug?
2.elasticsearch dsl get 10 items as default, how can I get other page or more than 10 items?

Thx

**Comment by alexgarel** [comment]
@playma 

1. use `restaurant_document.to_dict()`

2. `restaurant_document[start:end]`

I highly recommand you reading https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#

Good luck.

If you are satisfied, can you close the ticket ?

**Comment by alexgarel** [comment]
@safwanrahman you may close this ticket, I think :-)

**Comment by safwanrahman** [comment]
Thanks @alexgarel
