### ISSUE TITLE
'update' action on document fails - [UpdateRequest] unknown field [id], parser not found'

### ISSUE THREAD

**Issue by johnyoonh** [sabricot/django-elasticsearch-dsl#224]
``` 
   return bulk(client=self._get_connection(), actions=actions, **kwargs)
  File "venv/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 300, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "venv/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 230, in streaming_bulk
    **kwargs
  File "venv/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 116, in _process_bulk_chunk
    raise e
  File "venv/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 112, in _process_bulk_chunk
    resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
  File "venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "venv/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1505, in bulk
    headers={"content-type": "application/x-ndjson"},
  File "venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', '[1:2] [UpdateRequest] unknown field [id], parser not found')

bulk_actions 	

['{"update":{"_index":"article","_id":59}}',
 '{"owner":"epicskillshot","topic":"gaming","created":"2019-11-03T07:00:00+00:00","hotness":1.0']
```
Removing id from the prepared_field and other fields still result in the same error. The syntax for update has changed:

https://github.com/elastic/elasticsearch-py/issues/1042

django-elasticsearch-dsl            7.1.0    
django-elasticsearch-dsl-drf        0.20.2   
elasticsearch                       7.0.4    
elasticsearch-dsl                   7.1.0

**Comment by johnyoonh** [comment]
`_source` needs to be changed to `doc` when the action is `update`:
https://github.com/sabricot/django-elasticsearch-dsl/blob/3343e4d31850f2de83cab04080f52644ec8e6c6c/django_elasticsearch_dsl/documents.py#L165

**Comment by safwanrahman** [comment]
@johnyoonh Thanks for the report. Are you using parallal indexing?

**Comment by johnyoonh** [comment]
No, parallel is False. I am also overriding _prepare_action to specify which fields to update. There are just fields that do not need to be updated after initial index.

**Comment by safwanrahman** [comment]
@johnyoonh Is it possible to share your code? It will be interesting to see if there are any problem of the code. I have not got any issue updating with the vanilla `django-elasticsearch-dsl`

**Comment by johnyoonh** [comment]
I will see if I can share snippets of it. Which version of `django-elsaticsearch-dsl` are you using?

**Comment by safwanrahman** [comment]
@johnyoonh The latest version

**Comment by safwanrahman** [comment]
@johnyoonh Which version of elasticsearch you are using?

**Comment by johnyoonh** [comment]
This is one I am using:

{                                                        
  "name" : "juno",                                       
  "cluster_name" : "elasticsearch",                      
  "cluster_uuid" : "Az0otzmfQQOg_-0lsAuvkQ",             
  "version" : {                                          
    "number" : "7.1.1",                                  
    "build_flavor" : "default",                          
    "build_type" : "deb",                                
    "build_hash" : "7a013de",                            
    "build_date" : "2019-05-23T14:04:00.380842Z",        
    "build_snapshot" : false,                            
    "lucene_version" : "8.0.0",                          
    "minimum_wire_compatibility_version" : "6.8.0",      
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },                                                     
  "tagline" : "You Know, for Search"                     
}                                                        

I tested the same behavior on 7.4

**Comment by safwanrahman** [comment]
@johnyoonh I think you are making some mistake in overwriting the `_prepare_action` method. I think you add `"_op_type": "update"`, but we use `"_op_type": "index"` for new object as well as updating object. Using `_op_type` `index` works pretty well for our needs and it updates the exisiting document if the ID is matched. In the case of `_op_type` `index`, `_source` works just fine, but with `_op_type` `update`, it throws error. So I would recommend to use `_op_type` `index`.

**Comment by safwanrahman** [comment]
I have tried following to reproduce the issue
```python
from elasticsearch import Elasticsearch
es = Elasticsearch()
es.indices.create(index='test-index', ignore=400
es.create(index="test-index", body={"foo":"bar"}, id="test1")
data = {'_index': 'test-index',
 '_id': 'test1',
 'doc': {'foo': 'ddddsafwan'},
 '_op_type': 'index'}
bulk(es, actions=[data])
>> (1, [])
```
But if I change the `_op_type`
```python
data = {'_index': 'test-index',
 '_id': 'fooo',
 'doc': {'foo': 'ddddsafwan'},
 '_op_type': 'update'}
bulk(es, actions=[data])

# It raises error
>> RequestError(400, 'x_content_parse_exception', '[1:2] [UpdateRequest] unknown field [foo], parser not found')
```

**Comment by johnyoonh** [comment]
> There are just fields that do not need to be updated after initial index.

Okay we can call this, 'partial update' or 'patch'. I think patching is useful especially when the document has many complicated fields that do not change much.  Now that you know what I am after, I wonder what your opinion is on implementing such feature. It is supported by Elasticsearch.
