### ISSUE TITLE
Fix name resolution again

### ISSUE THREAD

**Issue by hirokbiswas** [sabricot/django-elasticsearch-dsl#227]
Elasticsearch_dsl.index. Index cannot be casted to string, `_name` property should be used instead.

Otherwise you'll see this in console:
`Deleting index '<elasticsearch_dsl.index.Index object at 0x7fb6a9c4a668>'`
`Creating index '<elasticsearch_dsl.index.Index object at 0x7fb6a9c7bf60>'`

Expected:
`Deleting index 'index_name_here'`
`Creating index 'index_name_here'`

**Comment by safwanrahman** [comment]
It has been fixed in latest version. Thanks!

**Comment by hirokbiswas** [comment]
I haven't found fixes in `7.1.0`. I have found name here https://github.com/sabricot/django-elasticsearch-dsl/pull/206/commits/67b80dac93d0d96ac94b7d5a4b996506a6de9c94 but not in 
`self.stdout.write("Deleting index '{}'".format(index))` same in _create()

**Comment by hirokbiswas** [comment]
@safwanrahman 
Mergeable PR https://github.com/sabricot/django-elasticsearch-dsl/pull/228

**Comment by safwanrahman** [comment]
@hirokbiswas Thanks a lot! 💯 
Merged, but you need to wait till next release. :shipit: 
fixed by #228
