### ISSUE TITLE
How to update/create index for particular documents? 

### ISSUE THREAD

**Issue by singhravi1** [sabricot/django-elasticsearch-dsl#236]
Lets suppose i have 1,000,000 documents indexed, Now if i have to update particular 1,00,000 documents, how can i do that?

**Comment by safwanrahman** [comment]
You can do that by passing the queryset to `MyDocument.update()`

**Comment by singhravi1** [comment]
Can we please add this to the documentation

**Comment by kos08001** [comment]
Documentation is also lacking delete
