### ISSUE TITLE
ModelFieldNotMappedError: Cannot convert model field vms to an Elasticsearch field!

### ISSUE THREAD

**Issue by prasad4491** [sabricot/django-elasticsearch-dsl#240]
I am getting following error

ModelFieldNotMappedError: Cannot convert model field vms to an Elasticsearch 

# models.py
`
from django.db import models
from django.contrib.auth.models import User

class VideoManagementSystem(models.Model):
    name = models.CharField(max_length=255)
    ip = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    type_properties = models.CharField(max_length=255)

    def __str__(self):
        return "Name: " + self.name + " Ip: " + self.ip

class Authentication(models.Model):
    type = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    vms = models.ForeignKey('VideoManagementSystem', on_delete=models.CASCADE, null=True, related_name='auths')

    def __str__(self):
        return self.type

class Camera(models.Model):
    name = models.CharField(max_length=255)
    identifier = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    type_properties = models.CharField(max_length=255)
    vms = models.ForeignKey('VideoManagementSystem', on_delete=models.CASCADE, null=True, related_name='cameras')

    def __str__(self):
        return self.name + str(self.vms)

# documents.py

from django_elasticsearch_dsl import Document, fields
from django_elasticsearch_dsl.registries import registry
from .models import VideoManagementSystem, Authentication, Camera

@registry.register_document
class VideoManagementSystemDocument(Document):
    
    class Index:
        # Name of the Elasticsearch index
        name = 'video_management_system'
        # See Elasticsearch Indices API reference for available settings
        settings = {'number_of_shards': 1,
                    'number_of_replicas': 0}

    class Django:
        model = VideoManagementSystem # The model associated with this Document

        # The fields of the model you want to be indexed in Elasticsearch
        fields = [
            'name',
            'ip',
            'type',
            'type_properties',
        ]

        # Ignore auto updating of Elasticsearch when a model is saved
        # or deleted:
        # ignore_signals = True

        # Don't perform an index refresh after every update (overrides global setting):
        # auto_refresh = False

        # Paginate the django queryset used to populate the index with the specified size
        # (by default it uses the database driver's default setting)
        # queryset_pagination = 5000

@registry.register_document
class AuthenticationDocument(Document):
    vms = fields.NestedField(properties={
        'name': fields.KeywordField(),
        'ip': fields.KeywordField(),
        'type': fields.KeywordField(),
        'type_properties': fields.TextField()
    })
    class Index:
        # Name of the Elasticsearch index
        name = 'authentication'
        # See Elasticsearch Indices API reference for available settings
        settings = {'number_of_shards': 1,
                    'number_of_replicas': 0}

    class Django:
        model = Authentication # The model associated with this Document

        # The fields of the model you want to be indexed in Elasticsearch
        fields = [
            'type',
            'username',
            'password'
        ]
        # Ignore auto updating of Elasticsearch when a model is saved
        # or deleted:
        # ignore_signals = True

        # Don't perform an index refresh after every update (overrides global setting):
        # auto_refresh = False

        # Paginate the django queryset used to populate the index with the specified size
        # (by default it uses the database driver's default setting)
        # queryset_pagination = 5000

@registry.register_document
class CameraDocument(Document):
    vms = fields.NestedField(properties={
        'name': fields.KeywordField(),
        'ip': fields.KeywordField(),
        'type': fields.KeywordField(),
        'type_properties': fields.TextField()
    })
    class Index:
        # Name of the Elasticsearch index
        name = 'camera'
        # See Elasticsearch Indices API reference for available settings
        settings = {'number_of_shards': 1,
                    'number_of_replicas': 0}

    class Django:
        model = Camera # The model associated with this Document

        # The fields of the model you want to be indexed in Elasticsearch
        fields = [
            'name',
            'identifier',
            'type',
            'type_properties'
        ]

        # Ignore auto updating of Elasticsearch when a model is saved
        # or deleted:
        # ignore_signals = True

        # Don't perform an index refresh after every update (overrides global setting):
        # auto_refresh = False

        # Paginate the django queryset used to populate the index with the specified size
        # (by default it uses the database driver's default setting)
        # queryset_pagination = 5000
`

**Comment by safwanrahman** [comment]
@prasad4491 django-elasticsearch-dsl does not know about how to populate the `vms` field.
You need to add a method named `prepare_vms` in document that will get the model instance and return the value that should be stored.

**Comment by prasad4491** [comment]
I have tried the following options. But I am getting the same issue.

  - def prepare_vms(self, instance):
        return {}

  - def prepare_vms_with_related(self, instance):
        return {}
