### ISSUE TITLE
Possible documentation error

### ISSUE THREAD

**Issue by jrief** [sabricot/django-elasticsearch-dsl#244]
In https://django-elasticsearch-dsl.readthedocs.io/en/latest/es_index.html the example states:

```
...

@registry.register_document
@car.document
class CarDocument(Document):
    class Django:
        model = Car
        fields = [
            'name',
            'color',
        ]
```

however, if I run `./manage.py search_index --rebuild`, I get an error such as
```
django_elasticsearch_dsl.exceptions.RedeclaredFieldError: You cannot ....
```

by removing `@registry.register_document` everything works fine. Is this intentional or a documentation bug?

**Comment by safwanrahman** [comment]
Can you provide the full stack trace?

**Comment by jrief** [comment]
sorry, seems to have been caused by some other problem.
