### ISSUE TITLE
StringField in documentation but gives an error

### ISSUE THREAD

**Issue by HenryMehta** [sabricot/django-elasticsearch-dsl#256]
On readthedocs (https://django-elasticsearch-dsl.readthedocs.io/en/latest/fields.html) the StringField is included in the list of Simple Fields at the bottom of the page but when I try and use it I get an Attribute Error.

> 
> AttributeError: module 'django_elasticsearch_dsl.fields' has no attribute 'StringField'
> 

I've subsequently noted that closed issues show it has been removed  but I cannot work out how to replace it with current functionality. 

I'm upgrading a very old program which used the StringField.  How do I replace it?  I've tried using a TextField but it seems to be breaking the string down into it's parts

**Comment by andreasnuesslein** [comment]
Hey @HenryMehta  you'll have to use `TextField`. The docs are upgraded but not rolled out yet 

https://github.com/sabricot/django-elasticsearch-dsl/commit/3eca047594f9871e734c3b97e5c5e35c6b52a907

**Comment by safwanrahman** [comment]
Oops! Seems like the build is failing on readthedocs. I will check and fix it! Thanks for the report @HenryMehta

**Comment by safwanrahman** [comment]
Fixed the build in readthedocs. The documentation should be fixed!
