### ISSUE TITLE
Can't index columns created by django-modeltranslation to Elastic, using django-elasticsearch-dsl

### ISSUE THREAD

**Issue by osxisl** [sabricot/django-elasticsearch-dsl#259]
I'm using django-modeltranslation to translate fields in Model.
And there is a problem with translation fields, as django-modeltranslation adds them to DB without changing original Model, so django-elasticsearch-dsl can't see them in Model.

I found an ugly workaround with turning off modeltranslation and editing models.py and document.py without making migrations and then reverting it back, but it's not a solution.
I've described problem in details [here](https://stackoverflow.com/questions/61123969/how-to-index-columns-created-by-django-modeltranslation-to-elastic-using-django)

Could someone help me to find a solution?

**Comment by safwanrahman** [comment]
@osxisl Thanks for the issue. But I do not think that fields that are not available in the model can be addressed by the scope of this package. Also I have very little idea about how the `django-modeltranslation` works. It would be better if you can use the `elasticsearch-dsl` directly for indexing the data.

Let me know if you have found any solution.

I am closing this as it is not the scope of this package.

**Comment by safwanrahman** [comment]
@osxisl As of your question, I have posted a answer there. I hope it will help! :)

**Comment by osxisl** [comment]
@safwanrahman thank you, it works now!

**Comment by ygag-ameer** [comment]
@safwanrahman what about when we want to index objectFields or NestedFields translation fields?
the answer you posted in stackoverflow is works in my model's translation field. but it did'nt work in objectFields and NestedFields
