### ISSUE TITLE
search_index --rebuild is missing documents

### ISSUE THREAD

**Issue by janoliver** [sabricot/django-elasticsearch-dsl#260]
I have a Model with about 15 million entries in the database. New objects appear every 20 minutes in bulk (a few hundred each time).

I have rebuilt the index several times now, and observed the following points:

- Each time the number of documents in elasticsearch ends up vastly different from the number of rows in my model table. One indexing, for instance, ended up having 17 million documents, another one ended up having only 14.5 million documents.
- Some documents are apparently always missing. I can't find error messages in the elastic log, and I'm not getting any error in the management command.

How can it be that elastic has more documents than rows in the Model table? Are there duplicates? Is that somehow intended? How can it be that documents are missing? Is there any fast and memory-friendly way of comparing the elastic index to the Model table? Is my assumption, that the number of elements in elastic should match the number of rows in the Model table exactly correct?

Thank you for the great work!

**Comment by alexgarel** [comment]
First think you should verify is that your ids (in ES) are unique. For if you use same id twice, ES simply overwrite the existing record, without any warning (this is the normal behaviour).

**Comment by janoliver** [comment]
I'm sorry, two issues on my behalf were the reason for seeing this strange behaviour (nested field -> more elastic docs than model rows, HDD full -> less elastic documents than 2x model rows). Closing this issue, thank you for your reply!
