### ISSUE TITLE
Error during --populate 

### ISSUE THREAD

**Issue by talvane** [sabricot/django-elasticsearch-dsl#261]
Hi, could someone help me understand this error below?

Your operating system name and version:
![image](https://user-images.githubusercontent.com/20425048/79142471-eee5f800-7d91-11ea-841a-c35de6b44844.png)

Any details about your local setup that might be helpful in troubleshooting:
-> elasticsearch==6.3.1
-> elasticsearch-dsl==6.1.0
-> django-elasticsearch-dsl==0.5.1

Detailed steps to reproduce the bug:
![Captura de tela de 2020-04-13 09-28-35](https://user-images.githubusercontent.com/20425048/79125929-55105200-7d75-11ea-9bf4-0efabe400749.png)

Tks to anyone who can help. :)

**Comment by alexgarel** [comment]
sorry @talvane but this is the wrong place to ask for questions. I'll ask you to post it on stackoverflow.

Also you should post you schema definition as it seems related to it (do you have such a field ?). Also post what you are trying to do, and the code that produce this bug (you code, not the library code).

**Comment by talvane** [comment]
Okay, thanks anyway.
