### ISSUE TITLE
search_index populate ignores prefetch_related

### ISSUE THREAD

**Issue by HansAdema** [sabricot/django-elasticsearch-dsl#27]
In most of my DocType classes, I extended `get_queryset` to add select_related and prefetch_related clauses to speed up indexing. The select_related clauses work fine, but since populate takes the iterator of the queryset, the prefetch_related clauses are ignored.

To help speed up indexing, it would help a lot of an alternative way to process the models could be used (like using pagination?).

Source: https://docs.djangoproject.com/en/1.8/ref/models/querysets/#django.db.models.query.QuerySet.iterator

**Comment by GeorgeLubaretsi** [comment]
Is this fixed by https://github.com/sabricot/django-elasticsearch-dsl/pull/29 ?

**Comment by HansAdema** [comment]
Yes, I believe this issue is fixed now with the above PR.

**Comment by singhravi1** [comment]
I'm facing this same issue with v7.1.0 again.
What could be the reason?

**Comment by safwanrahman** [comment]
@singhravi1 Are you facing it while running the management command?

**Comment by singhravi1** [comment]
@safwanrahman  Yes, i tried with both, `rebuild` and 'populate`

**Comment by safwanrahman** [comment]
@singhravi1 This is expected behavior as we are using `iterator` for optimization. You can overwrite the `get_indexing_queryset` in order to remove the iterator and get the prefetch related functionality

**Comment by singhravi1** [comment]
Okay. So `iterator` was removed and then re-introduced?
Cause `prefetch-related` was working when i used one of the 6.x.x version

**Comment by rabbagliettiandrea** [comment]
Wow guys, thank you so much for this issue!
What I was looking for is just:

`    def get_indexing_queryset(self):
        return self.get_queryset()
`

with this I can optimize my code with `prefetch_related()`!  :)
