### ISSUE TITLE
Future of this repo

### ISSUE THREAD

**Issue by prebenkeeeb** [sabricot/django-elasticsearch-dsl#270]
I saw the discussion in https://github.com/sabricot/django-elasticsearch-dsl/pull/254. I agree that the activity level is way to low in this project.
@sabricot will you create a new repo so more maintainers can be added? or would you recommend to use the fork https://github.com/django-elasticsearch/django-elasticsearch ?

**Comment by safwanrahman** [comment]
@prebenkeeeb I think you can use the fork if you are flexible with the future of that. The activity level can be low for various purpose but that does not make the future of this repository fade. You can ask to get your Pull Request reviewed, but in this scenario when everyone is going through a hard time, it is not desirable.

I am closing this issue as it is not related anything with this repository.
