### ISSUE TITLE
`multi_match` capability

### ISSUE THREAD

**Issue by frank-io** [sabricot/django-elasticsearch-dsl#273]
Hi, 

Just working on a project that needs a search functionality and looking for the capability of search multiple fields in the document with the same keyword. 

Does this package support that or ?

Many thanks
Frank

**Comment by safwanrahman** [comment]
Hi @frank-io,
I think you can use `multi_match` query of Elasticsearch.
You can see `elasticsearch-dsl` [documentation](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#queries) here.
