### ISSUE TITLE
are JoinFields supported?

### ISSUE THREAD

**Issue by dpinol** [sabricot/django-elasticsearch-dsl#275]
Hi,
join datatypes are used to model parent-child relationships
elasticsearch-dsl supports them:
https://github.com/elastic/elasticsearch-dsl-py/blob/master/examples/parent_child.py

are they supported by this project?

thanks

**Comment by alexgarel** [comment]
Hi @dpinol, as django-elasticsearch-dsl is just a wrapper around elasticsearch-dsl, it should work.

As far as I understand, the Join is only declarative to be able to use it in search.

If both objects are representations of a Django model, this should work out of the box. You should try on a toy example and report if you encounter problems.
