### ISSUE TITLE
Automatic indexing when object created

### ISSUE THREAD

**Issue by yarnball** [sabricot/django-elasticsearch-dsl#3]
Hi,

Great work on this project.

I am having trouble with automatically indexing newly created objects with `groupby`.

Every time a new model is created, it should index it.

However, it only indexes the "title" value. It does not index the "tag".

So, I created a manual function `manual_index`. When I run that, the "tag" value does get added to the index. However this process has to be manually triggered.

How can I get the "tag" value to save every time a new object is created?

***Search.py***

```
class TaskIndex(DocType):
    title = String()
    class Meta:
        index = 'task-index'

def manual_index():
    TaskIndex.init()
    es = Elasticsearch()
    bulk(client=es, actions=(b.indexing() for b in models.Task.objects.all().iterator()))
```

**Models.py**

```
from itertools import groupby

class Tag(models.Model):
    name = models.CharField("Name", max_length=5000, blank=True)
    taglevel = models.IntegerField("Tag level", null=True, blank=True)

class Item(models.Model):
    title = models.CharField("Title", max_length=10000, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)

    def get_grouped_tags(self):
        tag = self.tag.order_by('taglevel')
        grouped_tags = {
            tag_level: [
                { 'name': tag_of_level.name, 'taglevel': tag_of_level.taglevel, }
                for tag_of_level in tags_of_level
            ] for tag_level, tags_of_level
            in groupby(tag, lambda tag: tag.taglevel)
        }
        return grouped_tags

    def indexing(self):
        obj = TaskIndex(
            meta={'id': self.id},
            title=self.title,
            tag=self.get_grouped_tags()
        obj.save()
        return obj.to_dict(include_meta=True)
```

**Comment by sabricot** [comment]
hello,

I am not sure to understand  your problem but if your goal is to index in es your Item Model with its tags the  simplest solution is to store the tags as [elastisearch object](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/object.html) which lead to something like this.

**models.py**
```python
class Tag(models.Model):
    name = models.CharField("Name", max_length=5000, blank=True)
    taglevel = models.IntegerField("Tag level", null=True, blank=True)

class Item(models.Model):
    title = models.CharField("Title", max_length=10000, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)

    def tags(self):
        return self.tag.all()
```

**documents.py**
```python
item = Index('test_item')
item.settings(
    number_of_shards=1,
    number_of_replicas=0
)

@item.doc_type
class ItemDocument(DocType):
    tags = fields.ObjectField(properties={
        'name': fields.StringField(),
        'taglevel': fields.IntegerField(),
    })

    class Meta:
        model = Item
        fields = [
            'title',
        ]
```
With this, your items will be indexed at each save on the django Item model.
And for example you can query elasticsearch like this:
```python
results = ItemDocument.search().filter('term', **{'tags.taglevel': 4}

for doc in results:
    print(doc.title, doc.tags)
```
To get only items that have a tag with a taglevel of 4.

**Comment by yarnball** [comment]
Thanks but I'm not following how to implement that code.

I created a file called "documents.py" and added `import models` to it. 

But I do not know where the following belongs:

```
results = ItemDocument.search().filter('term', **{'tags.taglevel': 4}

for doc in results:
    print(doc.title, doc.tags)
```


Can you please advise? Also- I want it to return all levels of tags

**Comment by yarnball** [comment]
I found the solution- it was to use signals.

`m2m_changed.connect(update_search, sender=Item.tag.through)`
