### ISSUE TITLE
Support for I18N

### ISSUE THREAD

**Issue by eneepo** [sabricot/django-elasticsearch-dsl#37]
It would be really nice if I18N was supported for multilingual sites.

**Comment by sabricot** [comment]
Hello,

Do you have an idea of what it might look like ?

**Comment by eneepo** [comment]
Hello,

Yes, I have! 

Instead of a single index, having an index for each language specified in `settings.LANGUAGES` would be really nice. Language codes can be used as suffix.

When you try to rebuild the index using command line, `LANGUAGE_CODE` in django settings is used while I might need to rebuild the index with another language. It would be really nice if we could pass an argument to change the language. In most cases you can change the active translation for a model by using `django.utils.translation.activate`.

Also it would be really nice to disable/enable translation for a model or exclude/include fields.

Thanks for the awesome work, such a package was really needed!

**Comment by 3skr0** [comment]
IS there any workaround on this ?

**Comment by 3skr0** [comment]
using https://github.com/deschler/django-modeltranslation from @deschler

**Comment by sfausto** [comment]
@3skr0 did you find a solution for this?

**Comment by osxisl** [comment]
Hi, I'm having a similar issue as @3skr0 using django-modeltranslation.

I found an ugly workaround to make it work on development stage, but it can't be used for production. It described in my question [on stackoverflow](https://stackoverflow.com/questions/61123969/how-to-index-columns-created-by-django-modeltranslation-to-elastic-using-django)

@sabricot is there a way to make that django-elasticsearch-dsl can see the fields created not only with Model, but by django-modeltranslation to or index directly from DB?

**Comment by 3skr0** [comment]
found my code but not sure i understand something about it. 🤣 

I have 
`@register(Category)
class CategoryTranslationOptions(TranslationOptions):
	fields =('name','mini_description')
	#fallback_languages = {'default':('en',)}`

then 

`
    "default": {
        "ENGINE": "webapp.backend.MultilingualElasticsearchSearchEngine",
        "URL": "http://localhost:9200",
        "INDEX_NAME": "events_en",
    },
    "default_fr": {
        "ENGINE": "webapp.backend.MultilingualElasticsearchSearchEngine",
        "URL": "http://localhost:9200",
        "INDEX_NAME": "events_fr",
    },
    "default_en": {
        "ENGINE": "webapp.backend.MultilingualElasticsearchSearchEngine",
        "URL": "http://localhost:9200",
        "INDEX_NAME": "events_en",
    },
`

so i guess according to the language, i go on one or another elasticseach index.

**Comment by julianklotz** [comment]
Any idea how to make this work for generated fields like label_de/_en/_fr/...?

What I’ve been doing is something like that, not using ElasticSearch DSL:

* Implement a custom JSON serializer for documents
* Use "translatable=True" to indicate fields that are registered for translation (also using Django modeltranslation).

... but this is a custom implementation that doesn't work with ElasticSearch DSL. I prefer to use a single index for all languages and boost the fields for the current language per request to avoid having lots of indexes.

```
class SearchSerializer(AbstractSearchSerializer):
    identifier = fields.CharField('identifier')
    collection = fields.CharField('archive_collection_relation.identifier', 'archive_collection')
    label = fields.CharField('__str__', 'label', translatable=True)
    description = fields.CharField('description', translatable=True)
```
