### ISSUE TITLE
Cannot serialize ImageFieldFile

### ISSUE THREAD

**Issue by MightySCollins** [sabricot/django-elasticsearch-dsl#38]
Sorry to raise another issue, I tried looking though the source but could not find something I could easily to alter how it treats Django's ImageFieldFile. I keep getting the following error:

    elasticsearch.exceptions.SerializationError: ({'image': <ImageFieldFile: None>}, TypeError("Unable to serialize <ImageFieldFile: None> (type: <class 'django.db.models.fields.files.ImageFieldFile'>)",))

I tired setting the `attr` property to `image.url` like below but in the event a file does not exist Django will raise an error.
```python
image = fields.StringField(attr='image.url')
```

    ValueError: The 'image' attribute has no file associated with it.

Do you know of any solutions to this?

**Comment by sabricot** [comment]
Yes it's not manage right now. 

A workaround could be something like this:

Add to your document :
```
    def prepare_image(self, instance):
        return instance.image.url if instance.image else ''
```

**Comment by MightySCollins** [comment]
Yep that might work, I will try tomorrow. I might use a Try Except as it seems Django throws the ValueError.

**Comment by MightySCollins** [comment]
That solution works and I am happy with it. Ill close this but at some point it might be nice to have it built in.
