### ISSUE TITLE
How to use this pkg without model.?

### ISSUE THREAD

**Issue by vaibhav-jain** [sabricot/django-elasticsearch-dsl#39]
I have an usecase in which my user details are stored in PostgresSQL. Now i want to expose data already present in Elasticsearch using DRF. No models needed. But I like the idea of using something like ORM. Can you suggest something?

**Comment by barseghyanartur** [comment]
Weirdest question ever. Why would you use this package if you don't need model sync?

Why don't you use plain `elasticsearch-dsl` then?

**Comment by vaibhav-jain** [comment]
Seriously even I don't know why I asked this? My bad.
