### ISSUE TITLE
A way to programmatically create connection

### ISSUE THREAD

**Issue by andho** [sabricot/django-elasticsearch-dsl#40]
My app runs on ec2 and I'm running ES on AWS Elasticsearch. So basically I want to create an `http_auth` signature using boto3 to pass into the Elasticsearch instance. Is there a class I can extend (similar to `Elasticsearch2SearchBackend`) to programmatically create the connection?

**Comment by barseghyanartur** [comment]
@andho:

Can't you put it all into the [``settings.ELASTICSEARCH_DSL``](https://github.com/sabricot/django-elasticsearch-dsl/blob/master/django_elasticsearch_dsl/apps.py#L16)?

**Comment by andho** [comment]
@barseghyanartur I guess I could. The code will be as below:

    session = session.Session()
    credentials = session.get_credentials()
    region = session.region_name or settings.AWS_S3_REGION_NAME

    service = 'es'
    es_host = settings.ES_URL
    http_auth = AWSV4Sign(credentials, region, service)

    ELASTICSEARCH_DSL = {
        'default': {
            'host': ES_URL,
            'http_auth': http_auth,
        }
    }

Is it okay to make such requests in the `settings.py` file?

**Comment by barseghyanartur** [comment]
@andho:

Well, it depends on what kind of service it is. If it's a big service and you have to be able to release in seconds, serving millions of users, this approach might not be suitable for you. Otherwise - do it.

**Comment by andho** [comment]
Thanks for the help.

**Comment by kurtwheeler** [comment]
Hello, I used the code from the above example, however it appears that after some period of time the http_auth expires. Is there any way to get this to refresh it?
