### ISSUE TITLE
How to insert or update data?

### ISSUE THREAD

**Issue by gojuukaze** [sabricot/django-elasticsearch-dsl#41]
I want to insrt data like this
```
curl -XPOST http://localhost:9200/test/question_document/1533 -d'
{"title":"my title"}
'
```

can I insert data use Document?

**Comment by gojuukaze** [comment]
I have found update()

**Comment by sandino** [comment]
I've also found `update()` but have no idea how to use it. Can anyone give an example of the syntax, please?
