### ISSUE TITLE
NestedField seems to be broken

### ISSUE THREAD

**Issue by Rotyrap** [sabricot/django-elasticsearch-dsl#42]
Boiled down to its essential part my problem is that I can't get NestFields to work. 
At first I thought the problem was in my code but after copying and pasting the example from the documentation I still get the same error:

`django_elasticsearch_dsl.exceptions.VariableLookupError: Failed lookup for key [postsecondhand] in <Post: Post object>`

(these are my models but the error is the same. Just change Post with Car and postsecondhand with ads)

Any idea?

**Comment by alex-dotdev** [comment]
I think the example put the def in the wrong Class model. 

```
class Ad(models.Model):
    ...
    def ads(self):
        return self.ad_set.all()
```

It should be under the Car class.

```
class Car(models.Model):
    ...
    def ads(self):
        return self.ad_set.all()
```

**Comment by sabricot** [comment]
Yes? you are right. Thank you for the report, I fixed it.
