### ISSUE TITLE
[Doubt] - List of Priority 

### ISSUE THREAD

**Issue by robertomorati** [sabricot/django-elasticsearch-dsl#46]
Hi  @sabricot  

How are you?

I'd like to know if is possible to provide a list of priority, for example, id's of users, to be more fast in the search. 
For example: I typed keyword "Ana"... Thus will be returned the users with keyword "Ana" and that match with the list of priority (ids of users). After that, if not match any ID's of the priority list.... Thus, will be returned another results that match only keyword "Ana".

Thanks,
have a nice week,

**Comment by HansAdema** [comment]
Please note that this library mostly handles data synchronization between the Django ORM and Elasticsearch, it doesn't really do anything related to searching stuff.

If I were you, I'd check if Elasticsearch itself supports the kind of query you're looking for. If it does, you can probably compose a query for it with Elasticsearch DSL (again, not this library). And if Elasticsearch does not support it, I highly doubt a library for Elasticsearch could possibly ever support it.

**Comment by robertomorati** [comment]
Hi @sabricot @HansAdema  :)

In January I found the solution, but, unfortunately, I forgot to share my solution. I really really sorry!!!!!

> Solution: "def priority = params.priorities.get(doc['_uid'].value); if (priority == null) { return _score; } return priority;",

Follow:
`
            
            priorities = info_search['priorities']
            max_score = info_search['max_score']
            # create query
            q = query.Q(
                'function_score',
                query=query.Q('query_string', query=data_search + '*',
                              fields=['username', 'full_name'], default_operator="or",),
                functions=[
                    query.SF('script_score', script={
                        "lang": "painless",
                        'params': {'priorities': priorities},
                        'inline': "def priority = params.priorities.get(doc['_uid'].value); if (priority == null) { return _score; } return priority;",
                    })
                ],
                max_boost=float(models.PicPayPriority.objects.all().order_by('-weight').first().weight) + max_score,
                score_mode="max",
                boost_mode="replace",
                min_score=0.1
            )
            s = Search(index='pcusers-index').query(q)[int(limit * page):int((limit * (page + 1) - 1) + 1)]
            response = s.execute()
`

I believe that can be useful for the community :)

All the best,
Roberto Morati

**Comment by sabricot** [comment]
hello @robertomorati, thank you for the sharing :)
