### ISSUE TITLE
DocType is a bit hard to extend.

### ISSUE THREAD

**Issue by v1kku** [sabricot/django-elasticsearch-dsl#48]
This is because of how [DocTypeMeta creates an instance of DocType in its \_\_new\_\_ method](https://github.com/sabricot/django-elasticsearch-dsl/blob/7b83947d574702967141a7031a1743f6aeff1b76/django_elasticsearch_dsl/documents.py#L83). Creating an instance of the class inside it's Meta's \_\_new\_\_ should really not be happening.

If I create my own class that extends DocType like below

```
class OwnClass(DocType):
   def __init__(self, *args, **kwargs):
       super(OwnClass, self).__init__(*args, **kwargs)
```

This will raise an error as soon as you try to import this class. The error being that `OwnClass` does not exist. This is because we're referring to `OwnClass` in `super(OwnClass, self)` before it has been created. This also means that because an instance of the class is created before the class has been fully formed, referring to any of the attributes created after [that line in \_\_new\_\_](https://github.com/sabricot/django-elasticsearch-dsl/blob/7b83947d574702967141a7031a1743f6aeff1b76/django_elasticsearch_dsl/documents.py#L85-L107) in your \_\_init\_\_ function will raise an error.

**Comment by sabricot** [comment]
Thanks for the catch, you are absolulately right, there is no reason to instanciate the newly created class in the Meta's __new__. I am preparing a fix for it.
