### ISSUE TITLE
Analyzer is not being applied to fields?

### ISSUE THREAD

**Issue by ebsaral** [sabricot/django-elasticsearch-dsl#49]
```
contracts = Index('contracts')
my_analyzer = analyzer('simple')

contracts.analyzer(my_analyzer)


@contracts.doc_type
class ContractDocument(DocType):
    client = fields.StringField(attr='client_name')

    class Meta:
        model = Contract

        fields = [
            'id',
            'name'
        ]
```

I am trying to apply `simple` analyzer on fields. But when I call `termvectors` after running `search_index`, I see that `standard` analyzer is applied on fields. 

How can I apply `simple` analyzer to all fields?

I have tons of fields, I don't want to declare them by hand. Only solution is to create an ES Field for each model field? How can I declare analyzer for fields in `Meta.fields` or how can I modify my class to do this?

**Comment by sabricot** [comment]
If you are on es5, this could work.

```
default_analyzer = analyzer(
    'default',
    tokenizer="lowercase",
)
contracts.analyzer(default_analyzer)
```

**Comment by ebsaral** [comment]
@sabricot I tried that also. It didn't get applied to all fields unfortunately. Therefore I had to define analyzer for each StringField by overriding DocType and adding into each separate StringField.

**Comment by gkapatia** [comment]
I am facing same problem.
```question = Index('questions')
question.analyzer(questions_analyzer)```

but i see that analyzer is not being applied, but if I do what @ebsaral did, then analyzer is applied. Any help?
