### ISSUE TITLE
NestedField ads does not work in documents.py for the car model

### ISSUE THREAD

**Issue by codalprashant** [sabricot/django-elasticsearch-dsl#54]
Under CarDocument
ads = fields.NestedField(properties={
        'description': fields.StringField(analyzer=html_strip),
        'title': fields.StringField(),
        'pk': fields.IntegerField(),
    })

But when the ad is saved, no record is inserted in the car type. Let me know what I am lacking or there is something missing in the document itself.

**Comment by GeorgeLubaretsi** [comment]
Try adding `Ad` model to `related_models` in Document's Meta class.

**Comment by codalprashant** [comment]
Ya I did it. But it gives error in below function

def get_instances_from_related(self, related_instance):
        return related_instance.car_set.all()

saying car_set is not the option. 

Does anyone face this issue and solved it?

**Comment by codalprashant** [comment]
@alex-dotdev can you help me out in this ?

**Comment by alex-dotdev** [comment]
@codalprashant Returning `self` will resolve the submission errors in the Admin. But it's still not updating the index in Elastic.
```
@car.doc_type
class CarDocument(DocType):
    ads = fields.NestedField(properties={
        'title': fields.StringField(),
        'pk': fields.IntegerField(),
    })

    class Meta:
        model = Car
        related_models = [Ad]

    def get_instances_from_related(self, related_instance):
        return self
```

**Comment by alex-dotdev** [comment]
@codalprashant Testing via the Django shell with the settings above. `car.save()` works and updates the elastic index. It looks like the Signal aren't connect to the Admin panel. @sabricot Might been able to offer some advice quicker then myself.

**Comment by sabricot** [comment]
I have update the example app with a working example for this kind of relationship (when the foreign key is on the related model). 
You can check here https://github.com/sabricot/django-elasticsearch-dsl/blob/master/example/test_app/documents.py.

**Comment by codalprashant** [comment]
Finally Works. Thanks
