### ISSUE TITLE
Batching support on reindex

### ISSUE THREAD

**Issue by GeorgeLubaretsi** [sabricot/django-elasticsearch-dsl#55]
When indexing many entries (entire table reindex for example), support for batch data updates is crucial.

Django-haystack has support for this http://django-haystack.readthedocs.io/en/master/management_commands.html#rebuild-index

Here's how they do it:
https://github.com/django-haystack/django-haystack/blob/d69d4a152f7acf0bf69ab00a3e7bd11c8421e8f0/haystack/management/commands/update_index.py#L269

**Comment by sabricot** [comment]
You can add a property for this.
```
 class CarDocument(DocType):
    class Meta:
        ....
        queryset_pagination = 5000
```
