### ISSUE TITLE
Documentation doesn't explain how to do full-text search.

### ISSUE THREAD

**Issue by arielpontes** [sabricot/django-elasticsearch-dsl#56]
Absolutely all examples of searches in the documentation specify a field on which to perform the search. However, one of the popular features of Elasticsearch is full-text search. At least one example should be added to the documentation (if this package actually supports it, because it's not clear to me from the docs).

**Comment by barseghyanartur** [comment]
@arielpontes:

The purpose of this package is purely to allow easy indexing of Django models in the Elasticsearch.

For full text **search** examples or whatsoever, see the correspondent documentation of [Elasticsearch-DSL](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/full-text-queries.html) or [Elasticsearch-DSL Python](http://elasticsearch-dsl.readthedocs.io/en/latest/index.html) package.
