### ISSUE TITLE
Reverse relation does not update document

### ISSUE THREAD

**Issue by palqcho** [sabricot/django-elasticsearch-dsl#59]
In the #handle-relationship-with-nestedfieldobjectfield section of the README, we can see good example with three models: Car, Manufacturer and Ad. related_models makes sure that the Car will be re-saved when Manufacturer is updated.

Now I am struggling to make the Car re-saved when Ad is updated. It would be great if this is possible.

In other words, to trigger Car updates not only by models that Car has foreign key to, but by models that have Car as a foreign key.

**Comment by siddharthk-hashedin** [comment]
Have you found any solution for this problem?
