### ISSUE TITLE
Bulk save

### ISSUE THREAD

**Issue by caseydm** [sabricot/django-elasticsearch-dsl#68]
First off let me say this is an awesome python package. I'm trying to import 12 million records from a Heroku Postgres instance into Elastic Cloud, but it stops immediately due to an out of memory error. I think it's due to the way the normal `manage.py search_index --rebuild` works. Is there a way to easily implement a bulk save and batch the items or limit the memory use?

**Comment by sabricot** [comment]
If you add to your document:

```
class MyDocument(DocType):
    ....
    class Meta:
        ....
        queryset_pagination = 1000
```

Is it working ?  if not can you show me your models and document ?

**Comment by caseydm** [comment]
This worked perfectly, thank you!
