### ISSUE TITLE
Inherit model functions

### ISSUE THREAD

**Issue by caseydm** [sabricot/django-elasticsearch-dsl#70]
My django model (Employee) has functions such as `get_absolute_url()` that I would like to be available in my document model (EmployeeDocument). I was able to make this work by copying the function and placing it under the EmployeeDocument class. But this seems redundant. Can you think of a clean way to inherit all the functions from the primary model into the document model?

**Comment by sabricot** [comment]
When you define your field :
```
url = fields.StringField(attr="get_absolute_url")
```
