### ISSUE TITLE
to_queryset method failed

### ISSUE THREAD

**Issue by Hanyuusha** [sabricot/django-elasticsearch-dsl#72]
Django==2.0
django-elasticsearch-dsl==0.4.3
elasticsearch==5.5.1
elasticsearch-dsl==5.4.0

elasticsearch engine 5.0.0./5.1.1

to_queryset failed with:

RequestError                              Traceback (most recent call last)
<ipython-input-3-49fa52e10466> in <module>()
----> 1 s.to_queryset()

~/venvs/seostatistic/lib/python3.6/site-packages/django_elasticsearch_dsl/search.py in to_queryset(self, keep_order)
     **26             s = self.source(exclude=['*'])**
     27 
---> 28         pks = [result._id for result in s]
     29 
     30         qs = self._model.objects.filter(pk__in=pks)

~/venvs/seostatistic/lib/python3.6/site-packages/elasticsearch_dsl/search.py in __iter__(self)
    265         Iterate over the hits.
    266         """
--> 267         return iter(self.execute())
    268 
    269     def __getitem__(self, n):

~/venvs/seostatistic/lib/python3.6/site-packages/elasticsearch_dsl/search.py in execute(self, ignore_cache)
    637                     doc_type=self._doc_type,
    638                     body=self.to_dict(),
--> 639                     **self._params
    640                 )
    641             )

~/venvs/seostatistic/lib/python3.6/site-packages/elasticsearch/client/utils.py in _wrapped(*args, **kwargs)
     71                 if p in kwargs:
     72                     params[p] = kwargs.pop(p)
---> 73             return func(*args, params=params, **kwargs)
     74         return _wrapped
     75     return _wrapper

~/venvs/seostatistic/lib/python3.6/site-packages/elasticsearch/client/__init__.py in search(self, index, doc_type, body, params)
    630             index = '_all'
    631         return self.transport.perform_request('GET', _make_path(index,
--> 632             doc_type, '_search'), params=params, body=body)
    633 
    634     @query_params('_source', '_source_exclude', '_source_include',

~/venvs/seostatistic/lib/python3.6/site-packages/elasticsearch/transport.py in perform_request(self, method, url, params, body)
    310 
    311             try:
--> 312                 status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
    313 
    314             except TransportError as e:

~/venvs/seostatistic/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py in perform_request(self, method, url, params, body, timeout, ignore)
    126         if not (200 <= response.status < 300) and response.status not in ignore:
    127             self.log_request_fail(method, full_url, url, body, duration, response.status, raw_data)
--> 128             self._raise_error(response.status, raw_data)
    129 
    130         self.log_request_success(method, full_url, url, body, response.status,

~/venvs/seostatistic/lib/python3.6/site-packages/elasticsearch/connection/base.py in _raise_error(self, status_code, raw_data)
    123             logger.warning('Undecodable raw error response from server: %s', err)
    124 
--> 125         raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    126 
    127 

RequestError: TransportError(400, 'illegal_argument_exception', 'Deprecated field [exclude] used, expected [excludes] instead')

**Comment by sabricot** [comment]
Thank you for reporting, it was working for elasticsearch engine 5.0.0./5.1.0. 
Normaly it's fixed with 0.4.4
