### ISSUE TITLE
autofield mapping set to string, should be text

### ISSUE THREAD

**Issue by MSchietzsch** [sabricot/django-elasticsearch-dsl#76]
Just tested this wrapper after testing with the dsl. The default mapping of string from fields seems to be marked depcireded by elasticsearch 5.6.5

python manage.py search_index --rebuild

elasticsearch    | [2017-12-19T14:12:28,061][INFO ][o.e.c.m.MetaDataDeleteIndexService] [0CginTA] [stories/0aaM3MqDRgGfiiDkCkz9LA] deleting index
elasticsearch    | [2017-12-19T14:12:28,134][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] **The [string] field is deprecated, please use [text] or [keyword] instead on [story_title]**
elasticsearch    | [2017-12-19T14:12:28,135][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [auto_uid]
elasticsearch    | [2017-12-19T14:12:28,135][WARN ][o.e.d.i.m.StringFieldMapper$TypeParser] The [string] field is deprecated, please use [text] or [keyword] instead on [story_description]
elasticsearch    | [2017-12-19T14:12:28,150][INFO ][o.e.c.m.MetaDataCreateIndexService] [0CginTA] [stories] creating index, cause [api], templates [], shards [1]/[0], mappings [story_document]

**Comment by sabricot** [comment]
Yes i know this issue, it's kind of related to https://github.com/sabricot/django-elasticsearch-dsl/pull/62, StringField is deprecated in elasticsearch 5 https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_literal_string_literal_fields_replaced_by_literal_text_literal_literal_keyword_literal_fields. 
But the issue is I don't know by witch one replace it for es 5, TextField, KeywordField or both ?
Add a setting variable for choose the default string field ?

**Comment by MSchietzsch** [comment]
hmm I would think text is more general so more preferable as a default. But adding a setting to set this behaviour would be nice. Set it in default to text, so one could overwrite it to Keyword?

**Comment by caseydm** [comment]
Hi all. How can I set up my index with a textfield that also has a keywordfield available, similar to this article: https://www.elastic.co/blog/strings-are-dead-long-live-strings

**Comment by stevelacey** [comment]
You'll should read through the docs but the short answer is that for most purposes you want `TextField` but when you only want exact matches you want `KeywordField` – a good example is UUIDs that you may be storing as a string – a partial match of a UUID is pretty pointless

If you want to override the default mapping, the way I did this was by patching the dict Django-ESDL uses internally 😬 but it works well and got the job the done

```py
from django_elasticsearch_dsl import documents, fields
from django.contrib import postgres
from django.utils.functional import curry

from search.analyzers import standard


# Monkey patch model_field_class_to_field_class mapping so that we use
# Elasticsearch 5.0 text fields instead of deprecated string fields
documents.model_field_class_to_field_class.update({
    documents.models.CharField: curry(fields.TextField, analyzer=standard),
    documents.models.EmailField: fields.TextField,
    documents.models.FilePathField: fields.TextField,
    documents.models.SlugField: fields.TextField,
    documents.models.TextField: curry(fields.TextField, analyzer=standard),
    documents.models.URLField: fields.TextField,
    # Index ids as keyword fields so that they are not analysed
    documents.models.UUIDField: fields.KeywordField,
    # In our case, the array fields are all arrays of strings
    # We map this simply to a textfield; elasticsearch allows to index any value as array by default
    postgres.fields.ArrayField: curry(fields.TextField, analyzer=standard),
})
```

Note this is also a good way to add in extra fields such as Postgres-only fields like `ArrayField`, also you can use curry to add in custom analyzers... yeah, I was suprised it worked too 😀 but so good

**Comment by wflooney** [comment]
Steve, 
hi, i am just getting started with this library.   I am running a new version of elastic 6.2.2 so the string/CharField thing is urgent to me.

Where do you put your field conversion mapping  and how do you invoke it ?

I would like to use.  

Bill

**Comment by wflooney** [comment]
I added your function to my documents.py.  I removed the reference to search (not sure which package to use) and the postgres.

thanks for sharing your approach

**Comment by sabricot** [comment]
With the 0.5.0 used with ES 5/6 the default django string field is now mapped to an ES Textfield.
