### ISSUE TITLE
Add a global flag to ELASTICSEARCH_DSL setting which disables automatic indexing

### ISSUE THREAD

**Issue by markotibold** [sabricot/django-elasticsearch-dsl#8]
Hey,

In some cases it can be useful to disable the automatic indexing, for example when loading lots of fixtures. Or in our case when testing the success of fixture-loading in a CI environment with no ES backend.

Would you appreciate a pull request that implements such a flag?

**Comment by sabricot** [comment]
Hi,

Yes it's a good idea, if you want to implement it it will be with pleasure.

**Comment by markotibold** [comment]
Cool,

I'll come up with something soon.
