### ISSUE TITLE
How to write query using elasticsearch-dsl to bring all objects

### ISSUE THREAD

**Issue by siddharthk-hashedin** [sabricot/django-elasticsearch-dsl#93]
I tried doing 
MyDocument.search().query().using(client).execute() 
but its showing only 6 objects instead i have 6726 objects indexed.

**Comment by adrian410** [comment]
try this : 

s = MyDocument.search().query().using(client)
s = s[0:s.count()]

**Comment by siddharthk-hashedin** [comment]
Thanks !
