### ISSUE TITLE
Remove from index?

### ISSUE THREAD

**Issue by ckcollab** [sabricot/django-elasticsearch-dsl#95]
First of all: thanks for this project! We've been using it for a couple months and have found it very useful.

I was looking through the examples/docs to try and find how to remove a model from the index without actually deleting the model. My use case is we receive items to index, but sometimes those items become "hidden" and we want to remove them from the search (while keeping them in database to potentially re-enable later).

Is there a simple way to do this now?

For example:

```python
class MyModel(models.Model):
    def save(self, *args, **kwargs):
        self.some_signal_to_unindex = True
        super().save()
```

**Comment by jcushman** [comment]
Not an expert, but I was just looking for this. I think it's this:

`MyModelDocument().delete(id=instance.id)`

**Comment by safwanrahman** [comment]
I think its wise to have a boolean for hidden and remove from queryset. But if you want to remove it, maybe its better to use as following:
```
obj = Foo()
FooDocument.update(obj, action="delete")
```
